# -*- coding: utf-8 -*-
"""ENG4560 - Aula 11 - ILS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtPHc_5j7dFiKBczoRbrBYseHPEVo8SN

# **PUC-Rio | Departamento de Engenharia Industrial**
# **ENG 4560: Projeto Integrado VI - Distribuição Física**

---

# **Aula 11 — Metaheurísticas: Iterated Local Search (ILS)**
**Prof. Marcello Congro (marcellocongro@puc-rio.br)**

---

### Sprint 3 — Objetivo geral

Nas Sprints 1 e 2, construímos uma trajetória completa de resolução para o problema de roteirização da Prolog:

1. **Sprint 1** — Modelagem exata (CVRP com variáveis inteiras, solver).
2. **Sprint 2** — Heurísticas construtivas (Nearest Neighbor, Clarke-Wright) + Busca local (2-opt, Relocate).

A Sprint 2 entregou soluções de boa qualidade, mas com uma limitação conhecida: a **busca local para no primeiro ótimo local que encontra** e não consegue sair dele. Para instâncias maiores, esse ótimo local pode estar muito longe do ótimo global.

A **Sprint 3** responde com uma pergunta simples: *e se, ao chegar em um ótimo local, perturbássemos a solução e rodássemos a busca local novamente a partir desse novo ponto?* Essa ideia, repetida por muitas iterações, é o coração do **Iterated Local Search**.

---
> ⚠️ **Blocos TODO e GABARITO**
>
> Ao longo do notebook você encontrará trechos marcados com `# ── TODO (ALUNO) ──`.
> Esses trechos devem ser completados pela equipe antes de executar o ILS.
> Logo abaixo de cada TODO há um bloco `# [GABARITO]` **comentado** — tente implementar
> antes de consultá-lo.

## Seção 1 — Importações e carregamento da instância
"""

# ============================================================
# (1) IMPORTAÇÕES
# ============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
import os
import time
import copy
import random

from google.colab import files
from IPython.display import display

print("Bibliotecas importadas com sucesso.")

# ============================================================
# (2) UPLOAD DOS ARQUIVOS DA INSTÂNCIA E DA SOLUÇÃO INICIAL
# ============================================================
# Faça upload de:
#   nodes.csv, D.npy, Cvar.npy, q.npy, s.npy, params.json
# E de um arquivo de solução da Sprint 2:
#   solution_busca_local_final.json  (recomendado)
#   solution_cw_het.json
#   solution_nn_het.json

!rm -f *.csv *.npy *.json

print("Faça upload da instância e do arquivo JSON da solução inicial.")
uploaded = files.upload()

print("\nArquivos disponíveis no ambiente:")
print(os.listdir())

# ============================================================
# (3) LEITURA DA INSTÂNCIA
# ============================================================
nodes = pd.read_csv("nodes.csv")
D     = np.load("D.npy")
Cvar  = np.load("Cvar.npy")
q     = np.load("q.npy")
s     = np.load("s.npy")   # ATENÇÃO: s deve estar em HORAS.
                            # Se estiver em minutos no seu arquivo, divida por 60 abaixo:
                            # s = s / 60.0

with open("params.json", "r", encoding="utf-8") as f_params:
    params_raw = json.load(f_params)

n = len(nodes)

assert D.shape == (n, n),    f"Matriz D: esperado ({n},{n}), obtido {D.shape}"
assert Cvar.shape == (n, n), f"Matriz Cvar: esperado ({n},{n}), obtido {Cvar.shape}"
assert q.shape == (n,),      f"Vetor q: esperado ({n},), obtido {q.shape}"
assert s.shape == (n,),      f"Vetor s: esperado ({n},), obtido {s.shape}"

print(f"Instância carregada: {n-1} clientes + depósito (nó 0).")
print(f"Demanda total: {np.sum(q[1:]):.2f} kg")

# ============================================================
# (4) PARÂMETROS OPERACIONAIS
# ============================================================
# Mantemos os mesmos parâmetros das aulas anteriores.

params = {
    "capacity"  : {"FIO": 650.0,  "VUC": 3000.0},
    "fixed_cost": {"FIO": 250.0,  "VUC": 550.0},
    "cost_per_km": 1.50,
    "speed_kmh"  : 40.0,
    "max_hours"  : 8.0
}

print("Parâmetros operacionais:")
for k, v in params.items():
    print(f"  {k}: {v}")

"""## Seção 2 — Carregamento e padronização da solução inicial

O ILS é uma **metaheurística de melhoria** — ele não constrói soluções do zero,
ele as aprimora. Portanto, precisamos de uma solução inicial de qualidade.

Usaremos a melhor solução obtida na Sprint 2 (salva em JSON), que já passou por
heurística construtiva e busca local. Quanto melhor o ponto de partida, maior a
probabilidade de o ILS encontrar uma solução ainda melhor.

O JSON da solução tem o formato:
```json
[
  {"route": [0, 3, 7, 12, 0], "vehicle": "FIO"},
  {"route": [0, 1, 5, 9, 14, 0], "vehicle": "VUC"},
  ...
]
```

"""

# ============================================================
# (5) CARREGAMENTO DA SOLUÇÃO INICIAL
# ============================================================
solution_files = [
    f for f in os.listdir()
    if f.startswith("solution_") and f.endswith(".json")
]

if not solution_files:
    raise FileNotFoundError(
        "Nenhum arquivo de solução encontrado. "
        "Faça upload de solution_busca_local_final.json ou equivalente."
    )

print("Arquivos de solução encontrados:")
for idx, f in enumerate(solution_files):
    print(f"  {idx}: {f}")

# Selecione o índice do arquivo desejado:
selected_idx = 0
solution_filename = solution_files[selected_idx]

with open(solution_filename, "r", encoding="utf-8") as f_json:
    solution_loaded = json.load(f_json)

# Alguns arquivos salvam no formato {"solution": [...], "metadata": {...}}
if isinstance(solution_loaded, dict) and "solution" in solution_loaded:
    solution_loaded = solution_loaded["solution"]

print(f"\nArquivo selecionado: {solution_filename}")
print(f"Número de rotas: {len(solution_loaded)}")

# ============================================================
# (6) PADRONIZAÇÃO DA SOLUÇÃO
# ============================================================
# Garante que cada rota tenha: route_id, vehicle (maiúsculo), route.

def normalize_vehicle(v):
    v = str(v).upper()
    if v in ("FIO", "FIORINO"):
        return "FIO"
    elif v == "VUC":
        return "VUC"
    else:
        raise ValueError(f"Tipo de veículo desconhecido: {v}")

def normalize_solution(sol):
    return [
        {
            "route_id": item.get("route_id", idx + 1),
            "vehicle" : normalize_vehicle(item["vehicle"]),
            "route"   : item["route"]
        }
        for idx, item in enumerate(sol)
    ]

initial_solution = normalize_solution(solution_loaded)

print("Solução inicial padronizada:")
for item in initial_solution:
    n_cli = len([node for node in item["route"] if node != 0])
    print(f"  Rota {item['route_id']} | {item['vehicle']} | "
          f"{n_cli} clientes | sequência: {item['route']}")

# ============================================================
# (7) SEED PARA REPRODUTIBILIDADE
# ============================================================
# Metaheurísticas possuem componentes aleatórios.
# Fixar a seed garante que os resultados possam ser reproduzidos
# e comparados entre equipes de forma justa.

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

print(f"Seed fixada: {SEED}")
print("Todas as execuções com a mesma seed produzirão os mesmos resultados.")

"""## Seção 3 — Funções auxiliares reutilizadas

As funções abaixo foram desenvolvidas nas Aulas 7 e 8. Elas formam a
**infraestrutura de avaliação** do ILS — são chamadas centenas de vezes
por iteração, então estão escritas de forma enxuta.

> ⚠️ **Atenção às unidades:**
> - `D`: distâncias em **km**
> - `s`: tempos de serviço em **horas** (verifique a célula de carregamento)
> - `v_kmh`: velocidade em **km/h**
> - `H = 8.0`: jornada máxima em **horas**

"""

# ============================================================
# (8) FUNÇÕES DE ROTA
# ============================================================

def route_distance(route, D):
    """Distância total percorrida na rota (km), incluindo retorno ao depósito."""
    return sum(D[route[i], route[i+1]] for i in range(len(route)-1))


def route_load(route, q):
    """Carga total transportada (kg). Exclui o depósito (nó 0)."""
    return sum(q[node] for node in route if node != 0)


def route_service_time(route, s):
    """Tempo total de atendimento (horas). Exclui o depósito (nó 0)."""
    return sum(s[node] for node in route if node != 0)


def route_total_time(route, D, s, v_kmh):
    """
    Tempo total da rota (horas) = tempo de deslocamento + tempo de serviço.

    Retorna: (t_total, t_movimento, t_servico)

    Importante: s deve estar em HORAS. Se estiver em minutos, divida por 60
    na célula de carregamento antes de usar este notebook.
    """
    t_mov  = route_distance(route, D) / v_kmh
    t_serv = route_service_time(route, s)
    return t_mov + t_serv, t_mov, t_serv


def route_cost(route, vehicle_type, D, params):
    """Custo total da rota (R$) = custo fixo + custo variável por km."""
    clientes = [node for node in route if node != 0]
    if not clientes:
        return 0.0
    dist  = route_distance(route, D)
    fixed = params["fixed_cost"][vehicle_type]
    var   = params["cost_per_km"]
    return fixed + var * dist


def is_route_feasible(route, vehicle_type, D, q, s, params):
    """
    Verifica se a rota respeita as restrições operacionais:
    - capacidade máxima do veículo;
    - jornada máxima do motorista.
    """
    load_ok = route_load(route, q) <= params["capacity"][vehicle_type] + 1e-6
    t_total, _, _ = route_total_time(route, D, s, params["speed_kmh"])
    time_ok = t_total <= params["max_hours"] + 1e-6
    return load_ok and time_ok

print("Funções de rota definidas.")

# ============================================================
# (9) VERIFICAÇÃO GLOBAL DE VIABILIDADE
# ============================================================
# Em metaheurísticas, perturbações podem acidentalmente:
# - duplicar clientes;
# - remover clientes;
# - gerar rotas inviáveis.
#
# Esta função verifica a solução completa.

def is_solution_feasible(solution, D, q, s, params):
    """
    Retorna True se a solução:
    1. Cobre todos os clientes exatamente uma vez.
    2. Todas as rotas são individualmente viáveis.
    """
    visited = []
    for item in solution:
        if not is_route_feasible(item["route"], item["vehicle"], D, q, s, params):
            return False
        visited.extend(node for node in item["route"] if node != 0)

    expected = list(range(1, len(q)))
    return sorted(visited) == expected


print("Solução inicial viável?", is_solution_feasible(initial_solution, D, q, s, params))

# ============================================================
# (10) CUSTO TOTAL E MÉTRICAS DA SOLUÇÃO
# ============================================================

def total_solution_cost(solution, D, params):
    """Soma dos custos de todas as rotas (R$)."""
    return sum(route_cost(item["route"], item["vehicle"], D, params)
               for item in solution)


def solution_metrics(solution, D, q, s, params):
    """Dicionário com métricas consolidadas da solução."""
    n_fio = n_vuc = 0
    total_dist = total_cost = total_time = 0.0
    cap_viol = time_viol = 0

    for item in solution:
        route, veh = item["route"], item["vehicle"]
        dist  = route_distance(route, D)
        cost  = route_cost(route, veh, D, params)
        t, _, _ = route_total_time(route, D, s, params["speed_kmh"])

        total_dist += dist
        total_cost += cost
        total_time += t

        if veh == "FIO": n_fio += 1
        else:            n_vuc += 1

        if route_load(route, q) > params["capacity"][veh] + 1e-6:
            cap_viol += 1
        if t > params["max_hours"] + 1e-6:
            time_viol += 1

    return {
        "n_routes"           : len(solution),
        "n_fio"              : n_fio,
        "n_vuc"              : n_vuc,
        "total_distance_km"  : round(total_dist, 2),
        "total_cost_rs"      : round(total_cost, 2),
        "total_time_h"       : round(total_time, 2),
        "capacity_violations": cap_viol,
        "time_violations"    : time_viol,
    }


def build_solution_summary(solution, D, q, s, params):
    """DataFrame com uma linha por rota."""
    rows = []
    for item in solution:
        route, veh = item["route"], item["vehicle"]
        t, t_mov, t_serv = route_total_time(route, D, s, params["speed_kmh"])
        rows.append({
            "route_id"      : item["route_id"],
            "vehicle"       : veh,
            "n_clients"     : len([n for n in route if n != 0]),
            "load_kg"       : round(route_load(route, q), 2),
            "distance_km"   : round(route_distance(route, D), 2),
            "total_time_h"  : round(t, 2),
            "travel_time_h" : round(t_mov, 2),
            "service_time_h": round(t_serv, 2),
            "cost_rs"       : round(route_cost(route, veh, D, params), 2),
            "violates_H"    : t > params["max_hours"] + 1e-6,
        })
    return pd.DataFrame(rows)


metrics_initial = solution_metrics(initial_solution, D, q, s, params)
print("Métricas da solução inicial:")
for k, v in metrics_initial.items():
    print(f"  {k}: {v}")

# ============================================================
# (11) VISUALIZAÇÃO DA SOLUÇÃO
# ============================================================
# Adapte os nomes das colunas de coordenadas conforme seu nodes.csv.
# Opções comuns: "x"/"y", "lon"/"lat", "longitude"/"latitude".

COL_X = "lat"   # <<< ajuste se necessário
COL_Y = "lon"   # <<< ajuste se necessário

def plot_solution(solution, nodes, title):
    x = nodes[COL_X].values
    y = nodes[COL_Y].values

    plt.figure(figsize=(9, 9))
    plt.scatter(x[1:], y[1:], c="steelblue", s=50,  label="Clientes",  zorder=4)
    plt.scatter(x[0],  y[0],  c="red",       s=150, label="Depósito",  zorder=5,
                marker="*")

    first_fio = first_vuc = True
    for item in solution:
        route, veh = item["route"], item["vehicle"]
        ls    = "--" if veh == "FIO" else "-"
        label = None
        if veh == "FIO" and first_fio:
            label = "FIO"; first_fio = False
        elif veh == "VUC" and first_vuc:
            label = "VUC"; first_vuc = False
        for a in range(len(route)-1):
            plt.plot([x[route[a]], x[route[a+1]]],
                     [y[route[a]], y[route[a+1]]],
                     linestyle=ls, label=label if a == 0 else None, alpha=0.7)

    plt.title(title)
    plt.xlabel("X")
    plt.ylabel("Y")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.show()


plot_solution(initial_solution, nodes, "Solução inicial carregada")

"""## Seção 4 — Busca local como intensificação

No ILS, a busca local cumpre o papel de **intensificação**: partindo de qualquer
ponto do espaço de soluções, ela o conduz ao ótimo local mais próximo.

Isso acontece duas vezes em cada iteração do ILS:
1. Uma vez antes do laço principal (para partir de um ótimo local bem definido).
2. Uma vez após cada perturbação (para explorar o ótimo local da nova região).

Reutilizamos os três movimentos da Sprint 2:

| Movimento | Ação | Escopo |
|---|---|---|
| **2-opt** | Inverte um segmento da rota | Intra-rota |
| **Relocate** | Move um cliente para outra rota | Inter-rotas |
| **Swap** | Troca dois clientes entre rotas | Inter-rotas |

A função `local_search()` combina os três com flags booleanas.

"""

# ============================================================
# (12) MOVIMENTO 2-OPT
# ============================================================
# Inverte o segmento entre as posições i e k (inclusive).
# Exemplo: [0,A,B,C,D,0] com i=1, k=3 → [0,C,B,A,D,0]

def two_opt_swap(route, i, k):
    """Aplica um movimento 2-opt: inverte route[i:k+1]."""
    return route[:i] + route[i:k+1][::-1] + route[k+1:]


def improve_route_2opt(route, vehicle_type, D, q, s, params):
    """
    Aplica 2-opt exaustivo a uma única rota.
    Aceita o primeiro par (i,k) que reduza a distância e seja viável.
    Repete até não haver mais melhoria.
    """
    best_route = route[:]
    best_dist  = route_distance(best_route, D)
    improved   = True

    while improved:
        improved = False
        for i in range(1, len(best_route) - 2):
            for k in range(i + 1, len(best_route) - 1):
                candidate = two_opt_swap(best_route, i, k)
                if not is_route_feasible(candidate, vehicle_type, D, q, s, params):
                    continue
                cand_dist = route_distance(candidate, D)
                if cand_dist < best_dist - 1e-6:
                    best_route = candidate
                    best_dist  = cand_dist
                    improved   = True
                    break
            if improved:
                break

    return best_route


def apply_2opt(solution, D, q, s, params):
    """Aplica improve_route_2opt a cada rota da solução."""
    return [
        {**item, "route": improve_route_2opt(
            item["route"], item["vehicle"], D, q, s, params)}
        for item in solution
    ]

print("2-opt definido.")

# ============================================================
# (13) MOVIMENTO RELOCATE
# ============================================================
# Move um cliente de uma rota para outra (first improvement).

def relocate_customer(route_from, route_to, idx_from, idx_to):
    """
    Remove o cliente em idx_from de route_from e
    insere em idx_to de route_to.
    Retorna (nova_route_from, nova_route_to).
    """
    new_from = route_from[:]
    new_to   = route_to[:]
    customer = new_from.pop(idx_from)
    new_to.insert(idx_to, customer)
    return new_from, new_to


def apply_relocate(solution, D, q, s, params):
    """
    Relocate first-improvement entre todos os pares de rotas.
    Para quando encontra o primeiro movimento que reduz o custo total.
    """
    best      = copy.deepcopy(solution)
    best_cost = total_solution_cost(best, D, params)
    improved  = True

    while improved:
        improved = False
        for a in range(len(best)):
            if improved: break
            for b in range(len(best)):
                if improved or a == b: break
                r_from, r_to = best[a]["route"], best[b]["route"]
                for idx_from in range(1, len(r_from) - 1):
                    if improved: break
                    for idx_to in range(1, len(r_to)):
                        cand = copy.deepcopy(best)
                        nf, nt = relocate_customer(
                            cand[a]["route"], cand[b]["route"],
                            idx_from, idx_to)
                        cand[a]["route"] = nf
                        cand[b]["route"] = nt
                        # Remove rotas que ficaram sem clientes
                        cand = [item for item in cand
                                if any(node != 0 for node in item["route"])]
                        for rid, item in enumerate(cand, 1):
                            item["route_id"] = rid
                        if not is_solution_feasible(cand, D, q, s, params):
                            continue
                        cand_cost = total_solution_cost(cand, D, params)
                        if cand_cost < best_cost - 1e-6:
                            best, best_cost = cand, cand_cost
                            improved = True
                            break
    return best

print("Relocate definido.")

# ============================================================
# (14) MOVIMENTO SWAP
# ============================================================
# Troca dois clientes entre rotas distintas (first improvement).

def swap_customers(route_a, route_b, idx_a, idx_b):
    """
    Troca o cliente em idx_a de route_a pelo cliente em idx_b de route_b.
    Retorna (nova_route_a, nova_route_b).
    """
    new_a, new_b = route_a[:], route_b[:]
    new_a[idx_a], new_b[idx_b] = new_b[idx_b], new_a[idx_a]
    return new_a, new_b


def apply_swap(solution, D, q, s, params):
    """Swap first-improvement entre pares de rotas distintas."""
    best      = copy.deepcopy(solution)
    best_cost = total_solution_cost(best, D, params)
    improved  = True

    while improved:
        improved = False
        for a in range(len(best)):
            if improved: break
            for b in range(a + 1, len(best)):
                if improved: break
                r_a, r_b = best[a]["route"], best[b]["route"]
                for ia in range(1, len(r_a) - 1):
                    if improved: break
                    for ib in range(1, len(r_b) - 1):
                        cand = copy.deepcopy(best)
                        na, nb = swap_customers(
                            cand[a]["route"], cand[b]["route"], ia, ib)
                        cand[a]["route"] = na
                        cand[b]["route"] = nb
                        if not is_solution_feasible(cand, D, q, s, params):
                            continue
                        cand_cost = total_solution_cost(cand, D, params)
                        if cand_cost < best_cost - 1e-6:
                            best, best_cost = cand, cand_cost
                            improved = True
                            break
    return best

print("Swap definido.")

# ============================================================
# (15) BUSCA LOCAL COMPOSTA
# ============================================================
# Aplica os movimentos em sequência: 2-opt → Relocate → Swap.
# Cada operador pode ser ligado/desligado individualmente.

def local_search(solution, D, q, s, params,
                 use_2opt=True, use_relocate=True, use_swap=False):
    """
    Busca local composta.

    Parâmetros
    ----------
    use_2opt    : aplica 2-opt em cada rota
    use_relocate: aplica relocate entre rotas
    use_swap    : aplica swap entre rotas (desativado por padrão — mais lento)
    """
    current = copy.deepcopy(solution)

    if use_2opt:
        current = apply_2opt(current, D, q, s, params)

    if use_relocate:
        current = apply_relocate(current, D, q, s, params)

    if use_swap:
        current = apply_swap(current, D, q, s, params)

    return current

print("Busca local composta definida.")

"""## Seção 5 — Baseline: busca local standalone

Antes de aplicar o ILS, calculamos o **baseline**: a solução inicial submetida
à busca local sem nenhum mecanismo de perturbação.

Esse baseline tem dois papéis:
1. É o **ponto de partida** do ILS (o ILS parte daqui, não da solução bruta).
2. É a **referência de comparação**: o ganho que realmente importa é o do ILS
   sobre o baseline — não sobre a solução inicial bruta.

"""

# ============================================================
# (16) BASELINE: BUSCA LOCAL SEM ILS
# ============================================================
print("Calculando baseline (busca local standalone)...")

t0 = time.time()
baseline_solution = local_search(
    initial_solution, D, q, s, params,
    use_2opt=True, use_relocate=True, use_swap=False
)
t_baseline = time.time() - t0

metrics_baseline = solution_metrics(baseline_solution, D, q, s, params)

print(f"Baseline calculado em {t_baseline:.2f}s")
print("\nMétricas do baseline:")
for k, v in metrics_baseline.items():
    print(f"  {k}: {v}")

display(build_solution_summary(baseline_solution, D, q, s, params))
plot_solution(baseline_solution, nodes, "Baseline: busca local (sem ILS)")

"""## Seção 6 — O problema do ótimo local e a ideia do ILS

Após a busca local, chegamos a um **ótimo local** *S\**: uma solução tal que nenhum
movimento da vizinhança consegue melhorá-la. O algoritmo para — não porque encontrou
a melhor solução possível, mas porque ficou preso em um vale local do espaço de busca.

### Por que a busca local para onde para

Imagine o espaço de soluções como uma paisagem onde a altitude representa o custo.
A busca local é um caminhante que **sempre desce ladeira abaixo** e para ao chegar
a um vale. Esse vale pode ser raso — o vale mais profundo (ótimo global) pode estar
do outro lado de uma colina que o caminhante nunca subirá, pois a busca local nunca
aceita movimentos que piorem a solução.

### A estratégia do ILS

O **Iterated Local Search** resolve isso com um ciclo de cinco passos:

```
┌─────────────────────────────────────────────────────────┐
│  FLUXO DO ILS                                           │
│                                                         │
│  S₀ (solução inicial)                                  │
│       │                                                 │
│       ▼                                                 │
│  Busca local → S* (ótimo local)   ◄──────────┐         │
│       │                                       │         │
│       ▼                                       │         │
│  Perturbação(S*) → S'   ← diversificação      │         │
│       │                                       │         │
│       ▼                                       │         │
│  Busca local(S') → S''* ← intensificação      │         │
│       │                                       │         │
│       ▼                                       │         │
│  Critério de aceitação:                       │         │
│    aceita S''* como novo S*? ─────────────────┘         │
│       │                                                 │
│       ▼                                                 │
│  Atualiza melhor solução global se necessário           │
│       │                                                 │
│       ▼                                                 │
│  Repetir N iterações ou até limite de tempo             │
└─────────────────────────────────────────────────────────┘
```

A perturbação deve ser **forte o suficiente para sair do ótimo local atual**,
mas **fraca o suficiente para preservar estrutura da solução**. Esse equilíbrio
é o que diferencia uma boa perturbação de um reinício aleatório.

## Seção 7 — Perturbações

Implementamos três tipos de perturbação:

### P1 — Relocate aleatório
Move um cliente escolhido aleatoriamente para uma rota e posição aleatórias.
Não busca o melhor movimento — apenas um movimento aleatório válido.
Simples e rápido, mas pode não escapar de ótimos locais profundos.

### P2 — Swap aleatório
Troca dois clientes escolhidos aleatoriamente entre rotas distintas.
Mantém o número de clientes por rota aproximadamente estável.

### P3 — Double-bridge
A perturbação clássica para ILS em roteirização. Divide uma rota em 4 segmentos
e os reconecta em uma ordem que **nenhum movimento 2-opt consegue desfazer**.

Exemplo com clientes [A, B, C, D, E, F] e cortes em 1, 3, 5:
- seg1=[A], seg2=[B,C], seg3=[D,E], seg4=[F]
- Reconexão: seg1 + **seg3** + **seg2** + seg4 = [A, D, E, B, C, F]

Essa propriedade garante que a busca local após a double-bridge explore uma
**bacia de atração genuinamente diferente** da anterior.
"""

# ============================================================
# (17) PERTURBAÇÃO P1: RELOCATE ALEATÓRIO
# ============================================================

def perturb_relocate_random(solution, D, q, s, params, rng):
    """
    Move um cliente aleatório para uma rota e posição aleatórias.
    Retorna a solução perturbada se viável, ou a original se não.
    """
    candidate = copy.deepcopy(solution)

    # Rotas com pelo menos 1 cliente removível (tamanho > 2, pois [0,cliente,0])
    src_candidates = [
        idx for idx, item in enumerate(candidate)
        if len(item["route"]) > 3
    ]
    if not src_candidates:
        return candidate

    a   = rng.choice(src_candidates)
    b   = rng.randint(0, len(candidate) - 1)

    r_from = candidate[a]["route"]
    r_to   = candidate[b]["route"]

    if len(r_from) <= 2:
        return candidate

    idx_from = rng.randint(1, len(r_from) - 2)
    idx_to   = rng.randint(1, len(r_to) - 1)

    new_from, new_to = relocate_customer(r_from, r_to, idx_from, idx_to)
    candidate[a]["route"] = new_from
    candidate[b]["route"] = new_to

    # Remove rotas que ficaram sem clientes
    candidate = [item for item in candidate
                 if any(node != 0 for node in item["route"])]
    for rid, item in enumerate(candidate, 1):
        item["route_id"] = rid

    if is_solution_feasible(candidate, D, q, s, params):
        return candidate
    return copy.deepcopy(solution)   # fallback: retorna original se inviável


print("P1 (Relocate aleatório) definida.")

# ============================================================
# (18) PERTURBAÇÃO P2: SWAP ALEATÓRIO
# ============================================================

def perturb_swap_random(solution, D, q, s, params, rng):
    """
    Troca dois clientes aleatórios entre rotas distintas.
    Retorna a solução perturbada se viável, ou a original se não.
    """
    candidate = copy.deepcopy(solution)

    valid = [idx for idx, item in enumerate(candidate)
             if len(item["route"]) > 3]

    if len(valid) < 2:
        return candidate

    a, b = rng.sample(valid, 2)
    r_a  = candidate[a]["route"]
    r_b  = candidate[b]["route"]

    idx_a = rng.randint(1, len(r_a) - 2)
    idx_b = rng.randint(1, len(r_b) - 2)

    new_a, new_b = swap_customers(r_a, r_b, idx_a, idx_b)
    candidate[a]["route"] = new_a
    candidate[b]["route"] = new_b

    if is_solution_feasible(candidate, D, q, s, params):
        return candidate
    return copy.deepcopy(solution)


print("P2 (Swap aleatório) definida.")

# ============================================================
# (19) PERTURBAÇÃO P3: DOUBLE-BRIDGE
# ============================================================
# Divide os clientes de uma rota em 4 segmentos (A|B|C|D) e
# reconecta como A + C + B + D — operação não-reversível por 2-opt.
#
# Requer rota com pelo menos 4 clientes.
# Se nenhuma rota atender esse critério, usa P1 como fallback.

def perturb_double_bridge(solution, D, q, s, params, rng):
    """
    Double-bridge intra-rota.
    Retorna a solução perturbada se viável, ou a original se não.
    """
    candidate = copy.deepcopy(solution)

    # Rotas com >= 4 clientes (len(route) >= 6 contando os dois depósitos)
    valid = [idx for idx, item in enumerate(candidate)
             if len(item["route"]) >= 6]

    if not valid:
        # Fallback: usa relocate aleatório se nenhuma rota for longa o suficiente
        return perturb_relocate_random(solution, D, q, s, params, rng)

    r_idx   = rng.choice(valid)
    route   = candidate[r_idx]["route"]
    clients = route[1:-1]          # remove os dois depósitos
    n       = len(clients)

    # Escolhe 3 pontos de corte distintos em [1, n-1]
    if n < 4:
        return perturb_relocate_random(solution, D, q, s, params, rng)

    cuts      = sorted(rng.sample(range(1, n), 3))
    a, b, c   = cuts
    seg1, seg2, seg3, seg4 = clients[:a], clients[a:b], clients[b:c], clients[c:]

    # Reconexão double-bridge: seg1 + seg3 + seg2 + seg4
    new_route = [0] + seg1 + seg3 + seg2 + seg4 + [0]
    candidate[r_idx]["route"] = new_route

    if is_solution_feasible(candidate, D, q, s, params):
        return candidate
    return copy.deepcopy(solution)


print("P3 (Double-bridge) definida.")

# ============================================================
# (20) FUNÇÃO GERAL DE PERTURBAÇÃO
# ============================================================
# Dispatcher: seleciona a perturbação correta com base no parâmetro
# perturbation_type.
#
# Esta função é chamada pelo ILS a cada iteração.
# O restante do ILS não precisa saber qual perturbação está sendo usada.

def perturb_solution(solution, D, q, s, params, rng,
                     perturbation_type, perturbation_k=1):
    """
    Aplica a perturbação selecionada à solução.

    Parâmetros
    ----------
    perturbation_type : str
        'relocate_random', 'swap_random' ou 'double_bridge'
    perturbation_k : int
        Número de movimentos aleatórios para P1 e P2.
        Para double-bridge, k não é usado (a perturbação é fixa).
    """

    # ── Caso base fornecido como referência ───────────────────────
    if perturbation_type == 'relocate_random':
        # Aplica P1 k vezes consecutivas para aumentar a intensidade
        result = copy.deepcopy(solution)
        for _ in range(perturbation_k):
            result = perturb_relocate_random(result, D, q, s, params, rng)
        return result

    # ── TODO (ALUNO) ──────────────────────────────────────────────
    # Complete os casos para 'swap_random' e 'double_bridge'.
    # Siga o mesmo padrão do caso acima.
    #
    # Dicas:
    # - 'swap_random'   → chame perturb_swap_random (k vezes)
    # - 'double_bridge' → chame perturb_double_bridge (1 vez — k não se aplica)
    # ─────────────────────────────────────────────────────────────

    # [GABARITO]
    # elif perturbation_type == 'swap_random':
    #     result = copy.deepcopy(solution)
    #     for _ in range(perturbation_k):
    #         result = perturb_swap_random(result, D, q, s, params, rng)
    #     return result
    #
    # elif perturbation_type == 'double_bridge':
    #     return perturb_double_bridge(solution, D, q, s, params, rng)

    else:
        raise ValueError(
            f"Perturbação desconhecida: '{perturbation_type}'.\n"
            f"Opções válidas: 'relocate_random', 'swap_random', 'double_bridge'."
        )

print("Dispatcher de perturbações definido.")

"""## Seção 8 — Critério de aceitação

Após a perturbação + busca local, o ILS obtém uma nova solução *S''\**.
O **critério de aceitação** decide se *S''\** substitui a solução corrente *S\** para a
próxima iteração.

Dois critérios são implementados:

### Critério estrito (*strict*)
Aceita *S''\** apenas se for **estritamente melhor** que *S\* (custo menor).
Conservador — o algoritmo sempre trabalha a partir da melhor solução já encontrada.

### Critério com tolerância (*tolerance*)
Aceita *S''\** se o custo não exceder o custo corrente em mais de δ%.
Com δ=3%, aceita qualquer solução com custo ≤ custo_atual × 1.03.
Permite "subir pequenas colinas" para explorar regiões novas.

> ⚠️ **Isso não é Simulated Annealing.** No SA, a probabilidade de aceitar soluções piores
> diminui ao longo do tempo. Aqui, δ é **constante** durante toda a execução — é uma
> aceitação determinística com tolerância fixa.

"""

# ============================================================
# (21) CRITÉRIO DE ACEITAÇÃO   ← TODO 1
# ============================================================

def accept_solution(cost_new, cost_current, criterion, tolerance_pct=0.03):
    """
    Retorna True se a nova solução deve ser aceita como corrente.

    Parâmetros
    ----------
    cost_new      : custo da solução candidata (após perturbação + BL)
    cost_current  : custo da solução corrente
    criterion     : 'strict' ou 'tolerance'
    tolerance_pct : percentual de tolerância (ex: 0.03 para 3%)
    """

    if criterion == 'strict':
        return cost_new < cost_current - 1e-6

    elif criterion == 'tolerance':
        threshold = cost_current * (1.0 + tolerance_pct)
        return cost_new <= threshold

    else:
        raise ValueError(
            f"Critério inválido: '{criterion}'. Use 'strict' ou 'tolerance'."
        )


# ── Teste rápido ──────────────────────
print("Testando accept_solution:")
print("  strict,    melhora  :", accept_solution(900.0, 1000.0, 'strict'))
print("  strict,    piora    :", accept_solution(1050.0, 1000.0, 'strict'))
print("  tolerance, piora 2% :", accept_solution(1020.0, 1000.0, 'tolerance', 0.03))
print("  tolerance, piora 5% :", accept_solution(1050.0, 1000.0, 'tolerance', 0.03))

"""## Seção 9 — ILS completo

A função `iterated_local_search()` integra todos os componentes anteriores.

Ela retorna dois objetos:
1. **`best_solution`** — a melhor solução encontrada ao longo de *todas* as iterações.
2. **`history`** — lista de dicionários com custo corrente, melhor custo e tempo
   a cada iteração. É o que gera a curva de convergência.

> 💡 **Distinção importante:**
> - **Solução corrente**: de onde a próxima perturbação parte. Pode piorar com tolerância.
> - **Melhor solução global**: melhor já encontrada em qualquer iteração. **Nunca piora.**

"""

# ============================================================
# (22) ITERATED LOCAL SEARCH   ← TODO 2 e 3
# ============================================================

def iterated_local_search(
    initial_solution,
    D, q, s, params,
    # ── Perturbação ──────────────────────────────────────────
    perturbation_type = "relocate_random",
    perturbation_k    = 2,
    # ── Busca local ──────────────────────────────────────────
    use_2opt          = True,
    use_relocate      = True,
    use_swap          = False,
    # ── Aceitação ────────────────────────────────────────────
    accept_criterion  = "strict",
    tolerance_pct     = 0.03,
    # ── Parada ───────────────────────────────────────────────
    n_iterations      = 100,
    time_limit_sec    = None,
    # ── Misc ─────────────────────────────────────────────────
    seed              = 42,
    verbose           = True
):
    """
    Iterated Local Search para o CVRP da Prolog.

    Retorna (best_solution, history).
    """
    rng        = random.Random(seed)
    start_time = time.time()

    # ── Passo 1: busca local na solução inicial ───────────────
    current_solution = local_search(
        initial_solution, D, q, s, params,
        use_2opt, use_relocate, use_swap
    )
    current_cost = total_solution_cost(current_solution, D, params)

    best_solution = copy.deepcopy(current_solution)
    best_cost     = current_cost

    # ── Registro da iteração 0 (busca local inicial) ─────────
    history = [{
        "iteration"   : 0,
        "current_cost": current_cost,
        "best_cost"   : best_cost,
        "elapsed_sec" : 0.0,
        "accepted"    : True,          # a BL inicial é sempre aceita
    }]

    if verbose:
        print(f"{'Iter':>5} | {'Custo atual':>12} | {'Melhor':>12} | Aceito")
        print("-" * 50)
        print(f"{'0':>5} | R$ {current_cost:>9.2f} | R$ {best_cost:>9.2f} |  init")

    # ── Laço principal ────────────────────────────────────────
    for it in range(1, n_iterations + 1):

        # Verificação do limite de tempo
        elapsed = time.time() - start_time
        if time_limit_sec is not None and elapsed >= time_limit_sec:
            if verbose:
                print(f"\nLimite de tempo atingido ({elapsed:.1f}s) após {it-1} iterações.")
            break

        # ── Passo 2: perturbação ──────────────────────────────
        perturbed = perturb_solution(
            current_solution, D, q, s, params, rng,
            perturbation_type=perturbation_type,
            perturbation_k=perturbation_k
        )

        # ── Passo 3: busca local após perturbação ─────────────
        candidate      = local_search(perturbed, D, q, s, params,
                                      use_2opt, use_relocate, use_swap)
        candidate_cost = total_solution_cost(candidate, D, params)

        # ── TODO (ALUNO): Passos 4 e 5 ───────────────────────
        #
        # PASSO 4 — Critério de aceitação:
        #   Chame accept_solution com os argumentos corretos.
        #   Se aceito, atualize current_solution e current_cost.
        #
        # PASSO 5 — Atualização da melhor solução global:
        #   Se candidate_cost < best_cost, atualize best_solution e best_cost.
        #   Note: a atualização da melhor global é INDEPENDENTE da aceitação.
        #   (Uma solução pode ser o melhor já visto mesmo não sendo aceita como corrente.)
        #
        # Dica: use copy.deepcopy ao guardar a melhor solução.
        # ─────────────────────────────────────────────────────

        accepted = accept_solution(candidate_cost, current_cost,
                                  accept_criterion, tolerance_pct)
        if accepted:
             current_solution = copy.deepcopy(candidate)
             current_cost     = candidate_cost

        if candidate_cost < best_cost - 1e-6:
             best_solution = copy.deepcopy(candidate)
             best_cost     = candidate_cost

        # ── Registro do histórico ─────────────────────────────
        history.append({
            "iteration"   : it,
            "current_cost": current_cost,
            "best_cost"   : best_cost,
            "elapsed_sec" : time.time() - start_time,
            "accepted"    : accepted,
        })

        if verbose and (it <= 5 or it % 10 == 0):
            status = "✓" if accepted else "–"
            print(f"{it:>5} | R$ {current_cost:>9.2f} | R$ {best_cost:>9.2f} |  {status}")

    t_total = time.time() - start_time
    if verbose:
        ganho = (history[0]["current_cost"] - best_cost) / history[0]["current_cost"] * 100
        print("-" * 50)
        print(f"Concluído em {t_total:.1f}s | Melhor: R$ {best_cost:.2f} | "
              f"Ganho vs. BL inicial: {ganho:.1f}%")

    return best_solution, history

"""## Seção 10 — Configuração da equipe

**Altere apenas a variável `EQUIPE`** — os demais parâmetros são derivados automaticamente.

### Design experimental da Sprint 3

| | Aceitação **estrita** | Tolerância **δ=3%** |
|:---|:---:|:---:|
| **Relocate aleatório (k=2)** | A1 / B1 | A3 |
| **Double-bridge** | A2 / B2 | A4 / B3 |

Nas instâncias C1–C4, a busca local é fixa (2-opt + Relocate) para todas as equipes.
Só a perturbação e o critério de aceitação variam — isso é o que permite comparação justa.

"""

# ============================================================
# (23) CONFIGURAÇÃO DA EQUIPE
# ============================================================
# ╔═══════════════════════════════════════════════╗
# ║  ALTERE APENAS ESTA VARIÁVEL:                ║
# ╚═══════════════════════════════════════════════╝

EQUIPE = "A1"   # "A1" | "A2" | "A3" | "A4" | "B1" | "B2" | "B3"

# ════════════════════════════════════════════════════════════
# NÃO ALTERE ABAIXO DESTA LINHA
# ════════════════════════════════════════════════════════════
_CONFIGS = {
    # ── Turma A ─────────────────────────────────────────────
    "A1": dict(perturbation_type="relocate_random", perturbation_k=2,
               accept_criterion="strict",    tolerance_pct=0.00),
    "A2": dict(perturbation_type="double_bridge",   perturbation_k=1,
               accept_criterion="strict",    tolerance_pct=0.00),
    "A3": dict(perturbation_type="relocate_random", perturbation_k=2,
               accept_criterion="tolerance", tolerance_pct=0.03),
    "A4": dict(perturbation_type="double_bridge",   perturbation_k=1,
               accept_criterion="tolerance", tolerance_pct=0.03),
    # ── Turma B ─────────────────────────────────────────────
    "B1": dict(perturbation_type="relocate_random", perturbation_k=2,
               accept_criterion="strict",    tolerance_pct=0.00),
    "B2": dict(perturbation_type="double_bridge",   perturbation_k=1,
               accept_criterion="strict",    tolerance_pct=0.00),
    "B3": dict(perturbation_type="double_bridge",   perturbation_k=1,
               accept_criterion="tolerance", tolerance_pct=0.03),
}

cfg = _CONFIGS[EQUIPE]

# Parâmetros gerais do ILS (iguais para todas as equipes)
N_ITERATIONS   = 100
TIME_LIMIT_SEC = None    # None = usa n_iterations; valor em segundos para modo competição

USE_2OPT     = True
USE_RELOCATE = True
USE_SWAP     = False

print(f"Equipe selecionada: {EQUIPE}")
print(f"  Perturbação : {cfg['perturbation_type']} (k={cfg['perturbation_k']})")
print(f"  Aceitação   : {cfg['accept_criterion']}", end="")
if cfg['accept_criterion'] == 'tolerance':
    print(f" (δ = {cfg['tolerance_pct']*100:.0f}%)", end="")
print()
print(f"  Busca local : 2-opt={USE_2OPT}, Relocate={USE_RELOCATE}, Swap={USE_SWAP}")
print(f"  Iterações   : {N_ITERATIONS}")

"""## Seção 11 — Execução, análise e resultados

Execute as células abaixo em ordem após implementar todos os TODOs.

O processo tem três fases:
1. **Solução inicial** — carregada do JSON (calculada anteriormente).
2. **Baseline** — busca local standalone (já calculado na Seção 5).
3. **ILS** — algoritmo completo com a configuração da sua equipe.

A comparação **Baseline → ILS** é o indicador mais importante do valor adicionado
pela metaheurística.

"""

# ============================================================
# (24) EXECUÇÃO DO ILS
# ============================================================
print(f"Rodando ILS — Equipe {EQUIPE} | {N_ITERATIONS} iterações...")
print("=" * 60)

t0 = time.time()

solution_ils, history_ils = iterated_local_search(
    initial_solution = initial_solution,
    D=D, q=q, s=s, params=params,
    n_iterations     = N_ITERATIONS,
    time_limit_sec   = TIME_LIMIT_SEC,
    seed             = SEED,
    verbose          = True,
    use_2opt         = USE_2OPT,
    use_relocate     = USE_RELOCATE,
    use_swap         = USE_SWAP,
    **cfg             # desempacota perturbation_type, accept_criterion, tolerance_pct
)

t_ils = time.time() - t0
metrics_ils = solution_metrics(solution_ils, D, q, s, params)

print(f"\nTempo total do ILS: {t_ils:.2f}s")

# ============================================================
# (25) TABELA COMPARATIVA
# ============================================================
comparison = pd.DataFrame([
    {"Método": "Solução inicial (Sprint 2)",
     **{k: v for k, v in metrics_initial.items()}},
    {"Método": "Busca local (Baseline)",
     **{k: v for k, v in metrics_baseline.items()}},
    {"Método": f"ILS — Equipe {EQUIPE}",
     **{k: v for k, v in metrics_ils.items()}},
])

cols = ["Método","n_routes","n_fio","n_vuc",
        "total_distance_km","total_cost_rs","capacity_violations","time_violations"]
display(comparison[cols])

# ============================================================
# (26) GANHOS PERCENTUAIS
# ============================================================
c0  = metrics_initial["total_cost_rs"]
cbl = metrics_baseline["total_cost_rs"]
cils= metrics_ils["total_cost_rs"]

print(f"Ganho da busca local vs. solução inicial : {100*(c0-cbl)/c0:.2f}%")
print(f"Ganho do ILS vs. solução inicial         : {100*(c0-cils)/c0:.2f}%")
print(f"Ganho do ILS vs. busca local (baseline)  : {100*(cbl-cils)/cbl:.2f}%")
print()
print("Interpretação:")
print("  O ganho do ILS vs. baseline é o que realmente importa para a Sprint 3.")
print("  Ele mede o que a metaheurística acrescentou além da busca local simples.")

# ============================================================
# (27) CURVA DE CONVERGÊNCIA
# ============================================================
df_hist = pd.DataFrame(history_ils)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Gráfico 1: custo por iteração ────────────────────────────────────────────
ax = axes[0]
ax.plot(df_hist["iteration"], df_hist["current_cost"],
        color="steelblue", alpha=0.5, linewidth=0.9, label="Custo corrente")
ax.plot(df_hist["iteration"], df_hist["best_cost"],
        color="crimson",   linewidth=2.0,             label="Melhor custo")

# Marca iterações onde houve melhoria da melhor solução
melhorias = df_hist[df_hist["best_cost"] < df_hist["best_cost"].shift(1, fill_value=float('inf'))]
ax.scatter(melhorias["iteration"], melhorias["best_cost"],
           color="green", s=60, zorder=5, label="Nova melhor solução")

ax.set_xlabel("Iteração")
ax.set_ylabel("Custo total (R$)")
ax.set_title(f"Convergência — Equipe {EQUIPE}")
ax.legend()
ax.grid(True, alpha=0.3)

# ── Gráfico 2: melhor custo por tempo ────────────────────────────────────────
ax2 = axes[1]
ax2.plot(df_hist["elapsed_sec"], df_hist["best_cost"],
         color="crimson", linewidth=2.0)
ax2.set_xlabel("Tempo (s)")
ax2.set_ylabel("Melhor custo (R$)")
ax2.set_title("Melhor custo × Tempo")
ax2.grid(True, alpha=0.3)

plt.suptitle(f"ILS — Equipe {EQUIPE}", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

print(f"Melhorias encontradas: {len(melhorias)} em {N_ITERATIONS} iterações")
print(f"Última melhoria na iteração: {melhorias['iteration'].max() if not melhorias.empty else 'N/A'}")

# ============================================================
# (28) GRÁFICO DE BARRAS — COMPARAÇÃO ENTRE ETAPAS
# ============================================================
labels = ["Solução inicial", "Busca local\n(baseline)", f"ILS\n(Equipe {EQUIPE})"]
custos = [metrics_initial["total_cost_rs"],
          metrics_baseline["total_cost_rs"],
          metrics_ils["total_cost_rs"]]
cores  = ["#90CAF9", "#66BB6A", "#EF5350"]

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(labels, custos, color=cores, edgecolor="white", linewidth=1.2)
for bar, v in zip(bars, custos):
    ax.text(bar.get_x() + bar.get_width()/2,
            bar.get_height() + max(custos)*0.005,
            f"R$ {v:.0f}", ha="center", va="bottom", fontweight="bold")

ax.axhline(min(custos), color="gray", linestyle="--", alpha=0.5)
ax.set_ylabel("Custo total (R$)")
ax.set_title("Comparação entre etapas", fontweight="bold")
ax.set_ylim(min(custos)*0.88, max(custos)*1.08)
ax.grid(True, alpha=0.3, axis="y")
plt.tight_layout()
plt.show()

# ============================================================
# (29) VISUALIZAÇÃO DA SOLUÇÃO FINAL
# ============================================================
plot_solution(solution_ils, nodes, f"Solução ILS final — Equipe {EQUIPE}")
display(build_solution_summary(solution_ils, D, q, s, params))

# ============================================================
# (30) SALVAMENTO DA SOLUÇÃO E DO HISTÓRICO
# ============================================================
output_sol  = f"solution_ils_{EQUIPE}.json"
output_hist = f"history_ils_{EQUIPE}.csv"

with open(output_sol, "w", encoding="utf-8") as f_out:
    json.dump({
        "solution": solution_ils,
        "metadata": {
            "equipe"          : EQUIPE,
            "perturbation_type": cfg["perturbation_type"],
            "accept_criterion" : cfg["accept_criterion"],
            "tolerance_pct"    : cfg["tolerance_pct"],
            "n_iterations"     : N_ITERATIONS,
            "seed"             : SEED,
            "best_cost"        : metrics_ils["total_cost_rs"],
            "n_routes"         : metrics_ils["n_routes"],
        }
    }, f_out, indent=2, ensure_ascii=False)

df_hist.to_csv(output_hist, index=False)

files.download(output_sol)
files.download(output_hist)

print(f"Arquivos salvos:")
print(f"  {output_sol}  — solução final (submissão para a Sprint Review)")
print(f"  {output_hist} — histórico de convergência (para análise)")

"""## Seção 12 — Questões para o relatório da Sprint 3

Responda com base nos resultados obtidos neste notebook.
Cada resposta deve ser sustentada por dados: tabelas, gráficos e análise quantitativa.

---

**1.** O ILS melhorou a solução em relação à busca local standalone (baseline)?
Qual foi o ganho percentual? Esse ganho foi consistente ou variou por instância?

**2.** Em quantas iterações o ILS encontrou sua melhor solução? O algoritmo ainda
melhorava na última iteração, ou havia convergido? O que isso sugere sobre o número
ideal de iterações?

**3.** A curva de convergência mostra melhorias concentradas no início ou
distribuídas ao longo das iterações? O que isso revela sobre a eficácia da perturbação?

**4.** *(Para equipes com tolerância — A3, A4, B3)*: A linha do custo corrente
oscilou mais do que a das equipes com critério estrito? As oscilações levaram a
melhorias posteriores? A tolerância ajudou ou prejudicou o resultado final?

**5.** Qual foi o ganho do ILS em instâncias menores (C1, C2) versus maiores (C3, C4)?
O ILS escala bem com o tamanho do problema?

**6.** Considerando custo da solução, tempo computacional e robustez operacional,
qual configuração de algoritmo você recomendaria para a operação diária da Prolog?
Justifique em linguagem de negócio, não apenas técnica.

"""