# -*- coding: utf-8 -*-
"""ENG 4560 - Aula 12 - Análise de sensibilidade ILS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GheAicyxZvyM5_FqKbh-auqhNt0ZxuGl

# **PUC-Rio | Departamento de Engenharia Industrial**
# **ENG 4560: Projeto Integrado VI — Distribuição Física**

---

# **Aula 12 — Análise de Comportamento do ILS**
**Prof. Marcello Congro (marcellocongro@puc-rio.br)**

---

### Objetivo desta aula

Na Aula 11, você implementou o **Iterated Local Search** e obteve sua primeira solução.
Agora a pergunta muda de *"o algoritmo funciona?"* para *"como ele se comporta?"*

Esta aula tem três temas analíticos — todos com implicação direta no relatório da Sprint 3
e na decisão sobre qual configuração usar na competição:

| Seção | Tema | Pergunta central |
|---|---|---|
| 1 | **Análise de sensibilidade** | Como o resultado muda quando variamos `k` e `N`? |
| 2 | **Diagnóstico de convergência** | Quando o ILS "para de aprender"? |
| 3 | **Escalabilidade** | O ILS escala bem com instâncias maiores? |
| 4 | **Preparação para a competição** | Qual configuração levar para a instância COMP? |

---

> **Pré-requisito:** execute primeiro o notebook da Aula 11 para ter as funções
> e a solução baseline disponíveis. As funções `local_search`, `perturb_solution`,
> `accept_solution` e `iterated_local_search` devem estar definidas nesta sessão.

## Setup — importações e carregamento
"""

# ============================================================
# (0) LIMPEZA DO AMBIENTE ANTES DO UPLOAD
# ============================================================
# Execute esta célula antes de fazer upload dos arquivos.
# Ela remove arquivos antigos da instância para evitar conflitos como:
# D.npy, D (1).npy, D (2).npy, params (1).json etc.

import os
import glob
import shutil

padroes_para_remover = [
    "nodes*.csv",
    "D*.npy",
    "Cvar*.npy",
    "Tmov_h*.npy",
    "q*.npy",
    "s*.npy",
    "params*.json",
    "solution*.json",
    "*.zip",
    "__MACOSX"
]

for padrao in padroes_para_remover:
    for caminho in glob.glob(padrao):
        try:
            if os.path.isdir(caminho):
                shutil.rmtree(caminho)
            else:
                os.remove(caminho)
            print("Removido:", caminho)
        except Exception as e:
            print("Não foi possível remover:", caminho, "|", e)

print("\nLimpeza concluída.")
print("Agora execute a Célula 1 e faça upload dos arquivos corretos.")

# ============================================================
# (1) IMPORTAÇÕES, UPLOAD E CARREGAMENTO DOS ARQUIVOS
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import json, os, time, copy, random, math

from google.colab import files
from IPython.display import display

CORES = {
    'k1'      : '#2196F3',
    'k2'      : '#4CAF50',
    'k3'      : '#FF9800',
    'k4'      : '#E91E63',
    'melhor'  : '#E53935',
    'atual'   : '#90CAF9',
    'baseline': '#9E9E9E',
    'ils'     : '#2E7D32',
}

print("Faça upload dos arquivos da instância e da solução de busca local.")
print("Arquivos esperados:")
print("- nodes.csv")
print("- D.npy")
print("- Cvar.npy")
print("- q.npy")
print("- s.npy")
print("- params.json")
print("- solution_busca_local_final.json  ou outro JSON de solução")

uploaded = files.upload()

print("\nArquivos disponíveis no ambiente:")
print(os.listdir())

# ============================================================
# LEITURA DA INSTÂNCIA
# ============================================================

nodes = pd.read_csv("nodes.csv")
D = np.load("D.npy")
q = np.load("q.npy")
s = np.load("s.npy")

# Cvar é opcional para este notebook, pois o custo será calculado por distância.
# Mas carregamos se existir.
if os.path.exists("Cvar.npy"):
    Cvar = np.load("Cvar.npy")
else:
    Cvar = None

with open("params.json", "r", encoding="utf-8") as f:
    params_raw = json.load(f)

# ============================================================
# NORMALIZAÇÃO DOS PARÂMETROS
# ============================================================
# O objetivo é aceitar tanto o padrão das aulas:
# capacity, fixed_cost, cost_per_km, speed_kmh, max_hours
#
# quanto o padrão da instância secreta:
# VEHICLES, g_R$/km, v_kmh, H_horas

def normalize_params(params_raw):
    # Caso 1: padrão já usado nas aulas de heurísticas
    if all(k in params_raw for k in ["capacity", "fixed_cost", "cost_per_km", "speed_kmh", "max_hours"]):
        return {
            "capacity": params_raw["capacity"],
            "fixed_cost": params_raw["fixed_cost"],
            "cost_per_km": params_raw["cost_per_km"],
            "speed_kmh": params_raw["speed_kmh"],
            "max_hours": params_raw["max_hours"],
        }

    # Caso 2: padrão da instância secreta
    if "VEHICLES" in params_raw:
        vehicles = params_raw["VEHICLES"]

        capacity = {}
        fixed_cost = {}

        for key, val in vehicles.items():
            key_up = key.upper()

            if key_up in ["FIO", "FIORINO"]:
                name = "FIO"
            elif key_up == "VUC":
                name = "VUC"
            else:
                name = key_up

            capacity[name] = val.get("Q_kg", val.get("capacity", None))
            fixed_cost[name] = val.get("fixed_cost", val.get("custo_fixo_diario", None))

        return {
            "capacity": capacity,
            "fixed_cost": fixed_cost,
            "cost_per_km": params_raw.get("cost_per_km", params_raw.get("g_R$/km", 1.50)),
            "speed_kmh": params_raw.get("speed_kmh", params_raw.get("v_kmh", 40.0)),
            "max_hours": params_raw.get("max_hours", params_raw.get("H_horas", 8.0)),
        }

    raise ValueError("Formato de params.json não reconhecido.")

params = normalize_params(params_raw)

print("\nParâmetros operacionais normalizados:")
print(params)

# ============================================================
# LEITURA DA SOLUÇÃO BASELINE
# ============================================================

solution_files = [
    f for f in os.listdir()
    if f.endswith(".json") and f != "params.json"
]

if len(solution_files) == 0:
    raise FileNotFoundError(
        "Nenhum JSON de solução foi encontrado. "
        "Faça upload de solution_busca_local_final.json ou equivalente."
    )

print("\nArquivos JSON de solução encontrados:")
for i, f in enumerate(solution_files):
    print(i, "-", f)

# Escolhe automaticamente o primeiro JSON de solução.
# Se houver mais de um, altere selected_solution_file manualmente.
selected_solution_file = solution_files[0]

with open(selected_solution_file, "r", encoding="utf-8") as f:
    sol_json = json.load(f)

if isinstance(sol_json, dict) and "solution" in sol_json:
    baseline_solution = sol_json["solution"]
else:
    baseline_solution = sol_json

# Normaliza nomes de veículos e route_id
def normalize_vehicle_name(v):
    v = str(v).upper()
    if v in ["FIO", "FIORINO"]:
        return "FIO"
    elif v == "VUC":
        return "VUC"
    else:
        return v

def normalize_solution(solution):
    normalized = []

    for rid, item in enumerate(solution, start=1):
        normalized.append({
            "route_id": item.get("route_id", rid),
            "vehicle": normalize_vehicle_name(item["vehicle"]),
            "route": [int(x) for x in item["route"]]
        })

    return normalized

baseline_solution = normalize_solution(baseline_solution)

print("\nSolução baseline carregada:", selected_solution_file)
print("Número de rotas:", len(baseline_solution))
print("Clientes:", len(q) - 1)
print("Demanda total:", round(float(q[1:].sum()), 2), "kg")

# ============================================================
# (2) FUNÇÕES DE AVALIAÇÃO, BUSCA LOCAL E ILS
# ============================================================

def route_distance(route, D):
    return sum(D[route[i], route[i+1]] for i in range(len(route) - 1))

def route_load(route, q):
    return sum(q[nd] for nd in route if nd != 0)

def route_total_time(route, D, s, v_kmh):
    t_mov = route_distance(route, D) / v_kmh
    t_serv = sum(s[nd] for nd in route if nd != 0)
    return t_mov + t_serv, t_mov, t_serv

def route_cost(route, vehicle_type, D, params):
    if not any(nd != 0 for nd in route):
        return 0.0

    vehicle_type = normalize_vehicle_name(vehicle_type)
    dist = route_distance(route, D)

    return params["fixed_cost"][vehicle_type] + params["cost_per_km"] * dist

def total_solution_cost(solution, D, params):
    return sum(route_cost(r["route"], r["vehicle"], D, params) for r in solution)

def is_route_feasible(route, vehicle_type, D, q, s, params):
    vehicle_type = normalize_vehicle_name(vehicle_type)

    if route_load(route, q) > params["capacity"][vehicle_type] + 1e-6:
        return False

    t, _, _ = route_total_time(route, D, s, params["speed_kmh"])

    return t <= params["max_hours"] + 1e-6

def is_solution_feasible(solution, D, q, s, params, verbose=False):
    visited = []

    for r in solution:
        route = r["route"]
        vehicle = normalize_vehicle_name(r["vehicle"])

        if route[0] != 0 or route[-1] != 0:
            if verbose:
                print("Rota não começa/termina no depósito:", route)
            return False

        if not is_route_feasible(route, vehicle, D, q, s, params):
            if verbose:
                print("Rota inviável:", r)
                print("Carga:", route_load(route, q))
                print("Tempo:", route_total_time(route, D, s, params["speed_kmh"])[0])
            return False

        visited.extend(nd for nd in route if nd != 0)

    expected = list(range(1, len(q)))

    if sorted(visited) != expected:
        if verbose:
            print("Clientes visitados:", sorted(visited))
            print("Esperado:", expected)
        return False

    return True

def solution_metrics(solution, D, q, s, params):
    total_dist = 0.0
    total_time = 0.0
    total_cost = 0.0
    n_fio = 0
    n_vuc = 0

    for item in solution:
        route = item["route"]
        vehicle = normalize_vehicle_name(item["vehicle"])

        total_dist += route_distance(route, D)
        total_time += route_total_time(route, D, s, params["speed_kmh"])[0]
        total_cost += route_cost(route, vehicle, D, params)

        if vehicle == "FIO":
            n_fio += 1
        elif vehicle == "VUC":
            n_vuc += 1

    return {
        "n_routes": len(solution),
        "n_fio": n_fio,
        "n_vuc": n_vuc,
        "total_distance_km": total_dist,
        "total_time_h": total_time,
        "total_cost_rs": total_cost,
        "feasible": is_solution_feasible(solution, D, q, s, params)
    }

print("Baseline viável?", is_solution_feasible(baseline_solution, D, q, s, params, verbose=True))
print("Custo baseline:", round(total_solution_cost(baseline_solution, D, params), 2))
display(pd.DataFrame([solution_metrics(baseline_solution, D, q, s, params)]))

# ============================================================
# MOVIMENTOS DE BUSCA LOCAL
# ============================================================

def two_opt_swap(route, i, k):
    return route[:i] + route[i:k+1][::-1] + route[k+1:]

def improve_route_2opt(route, vehicle_type, D, q, s, params):
    best_route = route.copy()
    best_dist = route_distance(best_route, D)

    improved = True

    while improved:
        improved = False

        for i in range(1, len(best_route) - 2):
            for k in range(i + 1, len(best_route) - 1):
                candidate = two_opt_swap(best_route, i, k)

                if not is_route_feasible(candidate, vehicle_type, D, q, s, params):
                    continue

                candidate_dist = route_distance(candidate, D)

                if candidate_dist < best_dist - 1e-6:
                    best_route = candidate
                    best_dist = candidate_dist
                    improved = True
                    break

            if improved:
                break

    return best_route

def apply_2opt(solution, D, q, s, params):
    new_solution = []

    for item in solution:
        new_route = improve_route_2opt(
            route=item["route"],
            vehicle_type=item["vehicle"],
            D=D, q=q, s=s, params=params
        )

        new_solution.append({
            "route_id": item["route_id"],
            "vehicle": item["vehicle"],
            "route": new_route
        })

    return new_solution

def relocate_customer(route_from, route_to, idx_from, idx_to):
    new_from = route_from.copy()
    new_to = route_to.copy()

    customer = new_from.pop(idx_from)
    new_to.insert(idx_to, customer)

    return new_from, new_to

def apply_relocate(solution, D, q, s, params):
    best_solution = copy.deepcopy(solution)
    best_cost = total_solution_cost(best_solution, D, params)

    improved = True

    while improved:
        improved = False

        for a in range(len(best_solution)):
            route_from = best_solution[a]["route"]

            for b in range(len(best_solution)):
                if a == b:
                    continue

                route_to = best_solution[b]["route"]

                for idx_from in range(1, len(route_from) - 1):
                    for idx_to in range(1, len(route_to)):
                        candidate = copy.deepcopy(best_solution)

                        new_from, new_to = relocate_customer(
                            candidate[a]["route"],
                            candidate[b]["route"],
                            idx_from,
                            idx_to
                        )

                        candidate[a]["route"] = new_from
                        candidate[b]["route"] = new_to

                        candidate = [
                            item for item in candidate
                            if len([nd for nd in item["route"] if nd != 0]) > 0
                        ]

                        for rid, item in enumerate(candidate, start=1):
                            item["route_id"] = rid

                        if not is_solution_feasible(candidate, D, q, s, params):
                            continue

                        candidate_cost = total_solution_cost(candidate, D, params)

                        if candidate_cost < best_cost - 1e-6:
                            best_solution = copy.deepcopy(candidate)
                            best_cost = candidate_cost
                            improved = True
                            break

                    if improved:
                        break

                if improved:
                    break

            if improved:
                break

    return best_solution

def swap_customers(route_a, route_b, idx_a, idx_b):
    new_a = route_a.copy()
    new_b = route_b.copy()

    new_a[idx_a], new_b[idx_b] = new_b[idx_b], new_a[idx_a]

    return new_a, new_b

def apply_swap(solution, D, q, s, params):
    best_solution = copy.deepcopy(solution)
    best_cost = total_solution_cost(best_solution, D, params)

    improved = True

    while improved:
        improved = False

        for a in range(len(best_solution)):
            for b in range(a + 1, len(best_solution)):
                route_a = best_solution[a]["route"]
                route_b = best_solution[b]["route"]

                for idx_a in range(1, len(route_a) - 1):
                    for idx_b in range(1, len(route_b) - 1):
                        candidate = copy.deepcopy(best_solution)

                        new_a, new_b = swap_customers(
                            candidate[a]["route"],
                            candidate[b]["route"],
                            idx_a,
                            idx_b
                        )

                        candidate[a]["route"] = new_a
                        candidate[b]["route"] = new_b

                        if not is_solution_feasible(candidate, D, q, s, params):
                            continue

                        candidate_cost = total_solution_cost(candidate, D, params)

                        if candidate_cost < best_cost - 1e-6:
                            best_solution = copy.deepcopy(candidate)
                            best_cost = candidate_cost
                            improved = True
                            break

                    if improved:
                        break

                if improved:
                    break

            if improved:
                break

    return best_solution

def local_search(solution, D, q, s, params,
                 use_2opt=True,
                 use_relocate=True,
                 use_swap=False):

    current = copy.deepcopy(solution)

    if use_2opt:
        current = apply_2opt(current, D, q, s, params)

    if use_relocate:
        current = apply_relocate(current, D, q, s, params)

    if use_swap:
        current = apply_swap(current, D, q, s, params)

    return current

# ============================================================
# PERTURBAÇÕES
# ============================================================

def perturb_relocate_random(solution, D, q, s, params, rng, k=1):
    candidate = copy.deepcopy(solution)

    for _ in range(k):
        routes_with_clients = [
            idx for idx, item in enumerate(candidate)
            if len([nd for nd in item["route"] if nd != 0]) > 0
        ]

        if len(routes_with_clients) == 0:
            return copy.deepcopy(solution)

        a = rng.choice(routes_with_clients)
        b = rng.choice(range(len(candidate)))

        route_from = candidate[a]["route"]
        route_to = candidate[b]["route"]

        if len(route_from) <= 2:
            continue

        idx_from = rng.randint(1, len(route_from) - 2)
        idx_to = rng.randint(1, len(route_to) - 1)

        new_from, new_to = relocate_customer(route_from, route_to, idx_from, idx_to)

        candidate[a]["route"] = new_from
        candidate[b]["route"] = new_to

        candidate = [
            item for item in candidate
            if len([nd for nd in item["route"] if nd != 0]) > 0
        ]

        for rid, item in enumerate(candidate, start=1):
            item["route_id"] = rid

    if is_solution_feasible(candidate, D, q, s, params):
        return candidate

    return copy.deepcopy(solution)

def perturb_swap_random(solution, D, q, s, params, rng, k=1):
    candidate = copy.deepcopy(solution)

    for _ in range(k):
        valid_routes = [
            idx for idx, item in enumerate(candidate)
            if len(item["route"]) > 2
        ]

        if len(valid_routes) < 2:
            return copy.deepcopy(solution)

        a, b = rng.sample(valid_routes, 2)

        route_a = candidate[a]["route"]
        route_b = candidate[b]["route"]

        idx_a = rng.randint(1, len(route_a) - 2)
        idx_b = rng.randint(1, len(route_b) - 2)

        new_a, new_b = swap_customers(route_a, route_b, idx_a, idx_b)

        candidate[a]["route"] = new_a
        candidate[b]["route"] = new_b

    if is_solution_feasible(candidate, D, q, s, params):
        return candidate

    return copy.deepcopy(solution)

def perturb_double_bridge(solution, D, q, s, params, rng, k=1):
    candidate = copy.deepcopy(solution)

    for _ in range(k):
        valid_routes = [
            idx for idx, item in enumerate(candidate)
            if len([nd for nd in item["route"] if nd != 0]) >= 4
        ]

        if len(valid_routes) == 0:
            return copy.deepcopy(solution)

        r_idx = rng.choice(valid_routes)
        route = candidate[r_idx]["route"]
        clients = route[1:-1]

        if len(clients) < 4:
            continue

        cuts = sorted(rng.sample(range(1, len(clients)), 3))
        a, b, c = cuts

        part1 = clients[:a]
        part2 = clients[a:b]
        part3 = clients[b:c]
        part4 = clients[c:]

        new_clients = part1 + part3 + part2 + part4
        candidate[r_idx]["route"] = [0] + new_clients + [0]

    if is_solution_feasible(candidate, D, q, s, params):
        return candidate

    return copy.deepcopy(solution)

def perturb_solution(solution, D, q, s, params, rng,
                     perturbation_type="relocate_random",
                     perturbation_k=1):

    if perturbation_type == "relocate_random":
        return perturb_relocate_random(solution, D, q, s, params, rng, k=perturbation_k)

    elif perturbation_type == "swap_random":
        return perturb_swap_random(solution, D, q, s, params, rng, k=perturbation_k)

    elif perturbation_type == "double_bridge":
        return perturb_double_bridge(solution, D, q, s, params, rng, k=perturbation_k)

    else:
        raise ValueError(f"Perturbação desconhecida: {perturbation_type}")

# ============================================================
# ACEITAÇÃO E ILS
# ============================================================

def accept_solution(cost_new, cost_current, criterion="strict", tolerance_pct=0.03):
    if cost_new < cost_current - 1e-6:
        return True

    if criterion == "strict":
        return False

    elif criterion == "tolerance":
        return cost_new <= cost_current * (1.0 + tolerance_pct)

    else:
        raise ValueError(f"Critério inválido: {criterion}")

def iterated_local_search(initial_solution,
                          D, q, s, params,
                          n_iterations=100,
                          seed=42,
                          perturbation_type="relocate_random",
                          perturbation_k=1,
                          accept_criterion="strict",
                          tolerance_pct=0.03,
                          use_2opt=True,
                          use_relocate=True,
                          use_swap=False,
                          verbose=True):

    rng = random.Random(seed)
    start_time = time.time()

    current_solution = local_search(
        initial_solution, D, q, s, params,
        use_2opt=use_2opt,
        use_relocate=use_relocate,
        use_swap=use_swap
    )

    current_cost = total_solution_cost(current_solution, D, params)

    best_solution = copy.deepcopy(current_solution)
    best_cost = current_cost

    history = [{
        "iteration": 0,
        "current_cost": current_cost,
        "best_cost": best_cost,
        "accepted": True,
        "elapsed_sec": 0.0,
        "perturbation_type": perturbation_type,
        "accept_criterion": accept_criterion
    }]

    for it in range(1, n_iterations + 1):
        perturbed = perturb_solution(
            current_solution,
            D, q, s, params,
            rng=rng,
            perturbation_type=perturbation_type,
            perturbation_k=perturbation_k
        )

        improved = local_search(
            perturbed, D, q, s, params,
            use_2opt=use_2opt,
            use_relocate=use_relocate,
            use_swap=use_swap
        )

        candidate_cost = total_solution_cost(improved, D, params)

        accepted = accept_solution(
            cost_new=candidate_cost,
            cost_current=current_cost,
            criterion=accept_criterion,
            tolerance_pct=tolerance_pct
        )

        if accepted:
            current_solution = copy.deepcopy(improved)
            current_cost = candidate_cost

        if candidate_cost < best_cost - 1e-6:
            best_solution = copy.deepcopy(improved)
            best_cost = candidate_cost

        history.append({
            "iteration": it,
            "current_cost": current_cost,
            "best_cost": best_cost,
            "accepted": accepted,
            "elapsed_sec": time.time() - start_time,
            "perturbation_type": perturbation_type,
            "accept_criterion": accept_criterion
        })

        if verbose and it % 10 == 0:
            print(f"Iteração {it}: atual={current_cost:.2f}, melhor={best_cost:.2f}")

    return best_solution, history

print("Funções completas carregadas.")

# ============================================================
# (3) CONFIGURAÇÃO DOS EXPERIMENTOS
# ============================================================

INSTANCIA_TRABALHO = "Instância carregada"

K_VALORES = [1, 2, 3, 4]
N_FIXO = 80
SEED_FIXO = 42
ACCEPT = "strict"

PERTURBACAO = "relocate_random"  # opções: relocate_random, double_bridge, swap_random

custo_baseline = total_solution_cost(baseline_solution, D, params)

print(f"Instância de trabalho: {INSTANCIA_TRABALHO}")
print(f"Clientes: {len(q)-1}")
print(f"Demanda total: {q[1:].sum():.2f} kg")
print(f"Custo baseline carregado: R$ {custo_baseline:.2f}")
print(f"Perturbação inicial para sensibilidade: {PERTURBACAO}")

"""---
## Seção 1 — Análise de sensibilidade dos parâmetros

O ILS tem dois parâmetros principais que controlam sua exploração:
- **`k`** — intensidade da perturbação: quantos clientes são movidos aleatoriamente a cada iteração
- **`N`** — número de iterações: por quanto tempo o algoritmo continua tentando

A pergunta desta seção é: **quanto esses parâmetros importam?**

### Por que `k` importa

Uma perturbação muito fraca (`k=1`) pode não escapar do ótimo local — a busca local desfaz
o movimento e o algoritmo volta sempre ao mesmo ponto. Uma perturbação muito forte (`k` grande)
destrói a estrutura da solução e equivale a um reinício aleatório, perdendo o que foi aprendido.

Existe um valor de `k` que equilibra diversificação e preservação de estrutura.
Esse valor **depende da instância** — não existe resposta universal.

### Por que `N` importa — e tem retorno decrescente

Cada iteração adicional tem custo computacional fixo mas ganho esperado decrescente:
as primeiras iterações encontram melhorias fáceis (escapar dos piores ótimos locais);
as iterações tardias tentam ajustes cada vez mais finos em regiões já bem exploradas.

Há um ponto além do qual adicionar iterações não compensa. Identificá-lo é essencial
para uma recomendação operacional: quanto tempo a Prolog pode esperar pelo plano de rotas?

"""

# ============================================================
# (4) EXPERIMENTO 1 — EFEITO DE k
# ============================================================

resultados_k = {}

print(f"Experimento 1: efeito de k | perturbação={PERTURBACAO} | N={N_FIXO}")
print(f"{'k':>4} | {'Custo final (R$)':>17} | {'Ganho vs baseline':>18} | {'Tempo (s)':>10}")
print("-" * 62)

for k in K_VALORES:
    t0 = time.time()

    sol, hist = iterated_local_search(
        initial_solution=baseline_solution,
        D=D, q=q, s=s, params=params,
        perturbation_type=PERTURBACAO,
        perturbation_k=k,
        accept_criterion=ACCEPT,
        tolerance_pct=0.0,
        n_iterations=N_FIXO,
        seed=SEED_FIXO,
        verbose=False,
    )

    elapsed = time.time() - t0
    custo = total_solution_cost(sol, D, params)
    ganho = (custo_baseline - custo) / custo_baseline * 100

    resultados_k[k] = {
        "solution": sol,
        "history": hist,
        "custo": custo,
        "ganho": ganho,
        "tempo": elapsed
    }

    print(f"{k:>4} | R$ {custo:>13.2f} | {ganho:>16.2f}%  | {elapsed:>9.2f}s")

melhor_k = min(resultados_k, key=lambda k: resultados_k[k]["custo"])
print(f"\nMelhor k: {melhor_k} | custo R$ {resultados_k[melhor_k]['custo']:.2f}")

# ============================================================
# (5) GRÁFICOS — SENSIBILIDADE A k
# ============================================================

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

lista_cores = [CORES['k1'], CORES['k2'], CORES['k3'], CORES['k4']]

ax = axes[0]

for idx, k in enumerate(K_VALORES):
    hist = resultados_k[k]["history"]
    iters = [h["iteration"] for h in hist]
    bests = [h["best_cost"] for h in hist]

    ax.plot(
        iters,
        bests,
        color=lista_cores[idx],
        linewidth=2,
        label=f"k={k} → R$ {resultados_k[k]['custo']:.0f}"
    )

ax.axhline(
    custo_baseline,
    color=CORES['baseline'],
    linestyle='--',
    linewidth=1.2,
    label='Baseline'
)

ax.set_xlabel("Iteração")
ax.set_ylabel("Melhor custo (R$)")
ax.set_title(f"Convergência por intensidade de perturbação (k)\n{INSTANCIA_TRABALHO}")
ax.legend(fontsize=9)
ax.grid(True, alpha=0.3)

ax2 = axes[1]

custos = [resultados_k[k]["custo"] for k in K_VALORES]

bars = ax2.bar(
    [f"k={k}" for k in K_VALORES],
    custos,
    color=lista_cores,
    edgecolor='white',
    linewidth=1.2
)

for bar, v in zip(bars, custos):
    ax2.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + max(custos)*0.003,
        f"R$ {v:.0f}",
        ha='center',
        va='bottom',
        fontsize=9,
        fontweight='bold'
    )

ax2.axhline(
    custo_baseline,
    color=CORES['baseline'],
    linestyle='--',
    linewidth=1.2,
    label='Baseline'
)

ax2.set_ylabel("Custo final (R$)")
ax2.set_title(f"Custo final × intensidade de perturbação\n{INSTANCIA_TRABALHO}")
ax2.set_ylim(min(custos)*0.90, max(max(custos), custo_baseline)*1.06)
ax2.legend(fontsize=9)
ax2.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig("sensibilidade_k.png", dpi=150, bbox_inches='tight')
plt.show()

print("Gráfico salvo: sensibilidade_k.png")

# ============================================================
# (6) EXPERIMENTO 2 — EFEITO DE N
# ============================================================

N_VALORES = [20, 50, 100, 150, 200]
K_ESCOLHIDO = melhor_k

print(f"Experimento 2: efeito de N | k={K_ESCOLHIDO} | perturbação={PERTURBACAO}")
print(f"{'N':>5} | {'Custo final':>13} | {'Ganho vs BL':>12} | {'Tempo (s)':>10} | {'Ganho marginal':>15}")
print("-" * 72)

resultados_N = {}
custo_anterior = custo_baseline

for N in N_VALORES:
    t0 = time.time()

    sol, hist = iterated_local_search(
        initial_solution=baseline_solution,
        D=D, q=q, s=s, params=params,
        perturbation_type=PERTURBACAO,
        perturbation_k=K_ESCOLHIDO,
        accept_criterion=ACCEPT,
        tolerance_pct=0.0,
        n_iterations=N,
        seed=SEED_FIXO,
        verbose=False,
    )

    elapsed = time.time() - t0
    custo = total_solution_cost(sol, D, params)
    ganho = (custo_baseline - custo) / custo_baseline * 100
    marginal = custo_anterior - custo

    resultados_N[N] = {
        "solution": sol,
        "history": hist,
        "custo": custo,
        "ganho": ganho,
        "marginal": marginal,
        "tempo": elapsed
    }

    print(
        f"{N:>5} | R$ {custo:>10.2f} | {ganho:>10.2f}% | "
        f"{elapsed:>9.2f}s | R$ {marginal:>10.2f}"
    )

    custo_anterior = custo

# ============================================================
# (7) GRÁFICOS — SENSIBILIDADE A N
# ============================================================

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

ns = list(N_VALORES)
custos_N = [resultados_N[n]["custo"] for n in ns]

ax = axes[0]

ax.plot(ns, custos_N, 'o-', color=CORES['ils'], linewidth=2, markersize=7)

ax.axhline(
    custo_baseline,
    color=CORES['baseline'],
    linestyle='--',
    linewidth=1.2,
    label='Baseline'
)

ax.set_xlabel("N (número de iterações)")
ax.set_ylabel("Custo final (R$)")
ax.set_title(f"Custo final × número de iterações\n{INSTANCIA_TRABALHO} | k={K_ESCOLHIDO}")
ax.legend()
ax.grid(True, alpha=0.3)

for x, y in zip(ns, custos_N):
    ax.annotate(
        f"R${y:.0f}",
        (x, y),
        textcoords="offset points",
        xytext=(5, 5),
        fontsize=8
    )

ax2 = axes[1]

marginais = [resultados_N[n]["marginal"] for n in ns]

ax2.bar(
    [str(n) for n in ns],
    marginais,
    color=CORES['k2'],
    edgecolor='white'
)

ax2.axhline(0, color='black', linewidth=0.8)
ax2.set_xlabel("N (número de iterações)")
ax2.set_ylabel("Redução de custo adicional (R$)")
ax2.set_title("Ganho marginal por bloco de iterações")
ax2.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig("sensibilidade_N.png", dpi=150, bbox_inches='tight')
plt.show()

print("Ganho marginal como % do custo baseline:")
for n, marg in zip(ns, marginais):
    mp = abs(marg) / custo_baseline * 100
    flag = "← retorno decrescente" if mp < 0.5 else ""
    print(f"  N={n:>3}: {mp:.3f}% {flag}")

"""### O que devemos analisar?

Após rodar os experimentos acima, responda:

1. **Qual valor de `k` produziu o menor custo?** O resultado confirma a teoria de que perturbações muito fracas e muito fortes são piores?

2. **As curvas de convergência para diferentes `k` têm formatos distintos?** Uma perturbação mais agressiva melhora mais rápido mas estabiliza mais cedo?

3. **Qual é o ponto de retorno decrescente para `N`?** A partir de qual número de iterações o ganho marginal cai abaixo de 0,5% do custo?

4. **Qual combinação (k, N) você recomendaria** se a Prolog tiver restrição de tempo de 2 minutos para gerar o plano?

---
## Seção 2 — Diagnóstico de convergência

A **curva de convergência** conta a história do algoritmo: onde ele melhorou, onde ficou preso
e o que isso diz sobre a qualidade da solução final.

Mas há uma informação que a curva simples não mostra: **por quê o algoritmo parou de melhorar?**
Existem duas razões possíveis, com implicações diferentes:

**Razão A — Convergência genuína:** o algoritmo explorou bem o espaço e encontrou um bom ótimo
local. Rodar mais iterações não ajudaria muito. → Confie no resultado.

**Razão B — Estagnação prematura:** o algoritmo ficou preso num ótimo local ruim porque a
perturbação não foi forte o suficiente para escapar. Mais iterações *com perturbação mais forte*
poderiam ajudar. → Mude a configuração.

A diferença entre as duas se detecta analisando **quando a última melhoria aconteceu** e
**o que acontece com o custo corrente** após a última melhoria.

### Métrica: iteração da última melhoria

Se a última melhoria aconteceu na iteração 12 de 100, o algoritmo ficou 88 iterações sem
progredir. Isso é estagnação. Se aconteceu na iteração 94 de 100, o algoritmo ainda estava
aprendendo quando parou — precisaria de mais iterações.
"""

# ============================================================
# (8) DIAGNÓSTICO DE CONVERGÊNCIA
# ============================================================

EQUIPE = "A1"

_CONFIGS = {
    "A1": dict(perturbation_type="relocate_random", perturbation_k=2,
               accept_criterion="strict", tolerance_pct=0.00),
    "A2": dict(perturbation_type="double_bridge", perturbation_k=1,
               accept_criterion="strict", tolerance_pct=0.00),
    "A3": dict(perturbation_type="relocate_random", perturbation_k=2,
               accept_criterion="tolerance", tolerance_pct=0.03),
    "A4": dict(perturbation_type="double_bridge", perturbation_k=1,
               accept_criterion="tolerance", tolerance_pct=0.03),
    "B1": dict(perturbation_type="relocate_random", perturbation_k=2,
               accept_criterion="strict", tolerance_pct=0.00),
    "B2": dict(perturbation_type="double_bridge", perturbation_k=1,
               accept_criterion="strict", tolerance_pct=0.00),
    "B3": dict(perturbation_type="double_bridge", perturbation_k=1,
               accept_criterion="tolerance", tolerance_pct=0.03),
}

cfg = _CONFIGS[EQUIPE]
N_DIAG = 150

sol_diag, hist_diag = iterated_local_search(
    initial_solution=baseline_solution,
    D=D, q=q, s=s, params=params,
    n_iterations=N_DIAG,
    seed=SEED_FIXO,
    verbose=False,
    **cfg
)

df_hist = pd.DataFrame(hist_diag)

df_hist['nova_melhor'] = df_hist['best_cost'] < df_hist['best_cost'].shift(1, fill_value=float('inf'))

melhorias = df_hist[df_hist['nova_melhor']]

custo_inicial = df_hist.iloc[0]['current_cost']
custo_final = df_hist.iloc[-1]['best_cost']
n_melhorias = max(len(melhorias) - 1, 0)
ultima_melhora = int(melhorias.iloc[-1]['iteration']) if len(melhorias) > 1 else 0
ganho_total = (custo_inicial - custo_final) / custo_inicial * 100
pct_ociosa = (N_DIAG - ultima_melhora) / N_DIAG * 100

print(f"Equipe {EQUIPE} | {INSTANCIA_TRABALHO}")
print("─" * 50)
print(f"Custo inicial baseline : R$ {custo_inicial:.2f}")
print(f"Custo final ILS        : R$ {custo_final:.2f}")
print(f"Ganho total            : {ganho_total:.2f}%")
print(f"Número de melhorias    : {n_melhorias}")
print(f"Última melhoria        : iteração {ultima_melhora} / {N_DIAG}")
print(f"Iterações sem melhoria : {N_DIAG - ultima_melhora} ({pct_ociosa:.0f}% do total)")

if pct_ociosa > 50:
    print("\nDiagnóstico: ESTAGNAÇÃO — o algoritmo parou de melhorar cedo.")
elif pct_ociosa > 25:
    print("\nDiagnóstico: CONVERGÊNCIA PARCIAL — há alguma estagnação.")
else:
    print("\nDiagnóstico: CONVERGÊNCIA ATIVA — ainda melhorava no final.")

# ============================================================
# (9) GRÁFICO — PAINEL DE DIAGNÓSTICO
# ============================================================

fig = plt.figure(figsize=(14, 10))
gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.4, wspace=0.3)

ax1 = fig.add_subplot(gs[0, :])

iters = df_hist['iteration'].values
currnt = df_hist['current_cost'].values
best = df_hist['best_cost'].values

ax1.plot(
    iters,
    currnt,
    color=CORES['atual'],
    alpha=0.5,
    linewidth=0.9,
    label='Custo corrente'
)

ax1.plot(
    iters,
    best,
    color=CORES['melhor'],
    linewidth=2.2,
    label='Melhor custo'
)

if len(melhorias) > 1:
    ax1.scatter(
        melhorias['iteration'].iloc[1:],
        melhorias['best_cost'].iloc[1:],
        color='green',
        s=70,
        zorder=5,
        label='Nova melhor solução'
    )

ax1.axvline(
    ultima_melhora,
    color='navy',
    linestyle=':',
    linewidth=1.5,
    label=f'Última melhoria (iter {ultima_melhora})'
)

ax1.axhline(
    custo_inicial,
    color=CORES['baseline'],
    linestyle='--',
    linewidth=1.2,
    label='Baseline'
)

ax1.axvspan(
    ultima_melhora,
    N_DIAG,
    alpha=0.08,
    color='red'
)

ax1.set_xlabel("Iteração")
ax1.set_ylabel("Custo (R$)")
ax1.set_title(f"Curva de convergência completa — Equipe {EQUIPE} | {INSTANCIA_TRABALHO}", fontweight='bold')
ax1.legend(fontsize=9, loc='upper right')
ax1.grid(True, alpha=0.25)

ax2 = fig.add_subplot(gs[1, 0])

bloco = 10
df_hist_ls = df_hist[df_hist['iteration'] > 0].copy()
df_hist_ls['bloco'] = (df_hist_ls['iteration'] - 1) // bloco

taxa = df_hist_ls.groupby('bloco')['accepted'].mean() * 100

ax2.bar(
    taxa.index,
    taxa.values,
    color=CORES['k2'],
    edgecolor='white'
)

ax2.set_xlabel(f"Bloco de {bloco} iterações")
ax2.set_ylabel("Taxa de aceitação (%)")
ax2.set_title("Taxa de aceitação por bloco\n(quantas perturbações foram aceitas?)")
ax2.grid(True, alpha=0.3, axis='y')
ax2.set_ylim(0, 100)

ax3 = fig.add_subplot(gs[1, 1])

melhoria_acum = (custo_inicial - best) / custo_inicial * 100

ax3.plot(
    iters,
    melhoria_acum,
    color=CORES['ils'],
    linewidth=2
)

ax3.fill_between(
    iters,
    0,
    melhoria_acum,
    alpha=0.15,
    color=CORES['ils']
)

ax3.set_xlabel("Iteração")
ax3.set_ylabel("Melhoria acumulada vs. baseline (%)")
ax3.set_title("Ganho acumulado ao longo das iterações\n(curva de aprendizado do ILS)")
ax3.grid(True, alpha=0.3)

if melhoria_acum.max() > 0:
    ganho_90 = melhoria_acum.max() * 0.90
    iter_90 = iters[np.argmax(melhoria_acum >= ganho_90)]

    ax3.axhline(ganho_90, color='gray', linestyle=':', linewidth=1)
    ax3.annotate(
        f"90% do ganho total\n(iter {iter_90})",
        (iter_90, ganho_90),
        xytext=(iter_90 + max(N_DIAG * 0.05, 1), ganho_90),
        fontsize=8,
        arrowprops=dict(arrowstyle='->', color='gray')
    )
else:
    iter_90 = 0

plt.suptitle(
    f"Diagnóstico de convergência — Equipe {EQUIPE} | {INSTANCIA_TRABALHO}",
    fontsize=13,
    fontweight='bold',
    y=1.01
)

plt.savefig("diagnostico_convergencia.png", dpi=150, bbox_inches='tight')
plt.show()

print(f"90% do ganho total atingido na iteração {iter_90} de {N_DIAG}.")

# ============================================================
# (10) COMPARAÇÃO — STRICT VS TOLERANCE
# ============================================================

print("Comparando strict vs. tolerance...")

resultados_aceit = {}

for criterio, delta in [("strict", 0.0), ("tolerance", 0.03)]:
    _, hist = iterated_local_search(
        initial_solution=baseline_solution,
        D=D, q=q, s=s, params=params,
        perturbation_type=cfg['perturbation_type'],
        perturbation_k=cfg['perturbation_k'],
        accept_criterion=criterio,
        tolerance_pct=delta,
        n_iterations=N_DIAG,
        seed=SEED_FIXO,
        verbose=False,
    )

    resultados_aceit[criterio] = pd.DataFrame(hist)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for ax, col, label in [
    (axes[0], 'current_cost', 'Custo corrente'),
    (axes[1], 'best_cost', 'Melhor custo')
]:
    for criterio, cor in [("strict", CORES['k1']), ("tolerance", CORES['k3'])]:
        df_plot = resultados_aceit[criterio]
        custo_fin = df_plot.iloc[-1]['best_cost']

        ax.plot(
            df_plot['iteration'],
            df_plot[col],
            color=cor,
            linewidth=1.8,
            alpha=0.85 if col == 'best_cost' else 0.55,
            label=f"{criterio} → R$ {custo_fin:.0f}"
        )

    ax.axhline(
        custo_inicial,
        color=CORES['baseline'],
        linestyle='--',
        linewidth=1.2,
        label='Baseline'
    )

    ax.set_xlabel("Iteração")
    ax.set_ylabel(f"{label} (R$)")
    ax.set_title(f"{label}\nstrict vs. tolerance")
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.25)

plt.suptitle(
    f"Efeito do critério de aceitação — {INSTANCIA_TRABALHO}",
    fontsize=12,
    fontweight='bold'
)

plt.tight_layout()
plt.savefig("comparacao_criterios.png", dpi=150, bbox_inches='tight')
plt.show()

for criterio in ["strict", "tolerance"]:
    df_plot = resultados_aceit[criterio]
    cf = df_plot.iloc[-1]['best_cost']
    g = (custo_inicial - cf) / custo_inicial * 100
    ta = df_plot[df_plot['iteration'] > 0]['accepted'].mean() * 100

    print(f"{criterio:<12}: custo={cf:.2f} | ganho={g:.2f}% | aceitação={ta:.1f}%")

"""### Quais perguntas devem ser respondidas na análise?

1. **Qual o diagnóstico do seu algoritmo?** Convergência genuína, convergência parcial ou estagnação prematura?

2. **Em quantas iterações foi atingido 90% do ganho total?** O que isso sugere sobre o custo-benefício de N?

3. **A taxa de aceitação caiu ao longo das iterações?** Uma queda progressiva indica que o algoritmo está explorando regiões de custo cada vez mais parecido — sinal de convergência.

4. **No gráfico de strict vs. tolerance:** o critério de tolerância produziu custo corrente mais oscilante? Essa oscilação resultou em melhor custo final, ou foi ruído sem benefício?

---
## Seção 3 — Escalabilidade: o ILS funciona igual para instâncias maiores?

Nas Seções 1 e 2, trabalhamos com uma única instância. Mas a Prolog não tem sempre o mesmo
número de clientes por dia — a demanda varia, e o algoritmo precisa funcionar bem em diferentes
escalas.

**Escalabilidade** responde a duas perguntas práticas:

1. **O ganho do ILS sobre o baseline cresce ou encolhe com instâncias maiores?**
   Se o ILS ajuda mais em instâncias grandes, ele é mais valioso exatamente quando mais precisa.

2. **O tempo computacional cresce de forma aceitável?**
   Um algoritmo que funciona bem em C2 mas demora 30 minutos em C4 pode não ser viável
   operacionalmente.

### A teoria por trás

Em instâncias pequenas, o espaço de soluções é limitado — a busca local já encontra bons ótimos
locais por conta própria, e o ILS acrescenta pouco. Em instâncias maiores, o espaço de soluções
cresce exponencialmente, os ótimos locais ficam mais distantes entre si, e a perturbação do ILS
torna-se mais valiosa para escapar de regiões ruins.

Se os dados confirmarem isso, temos um argumento forte para a Prolog: *"quanto maior a operação,
mais o ILS vale a pena"*.
"""

# ============================================================
# (11) UPLOAD DAS INSTÂNCIAS PARA ANÁLISE DE ESCALABILIDADE
# ============================================================
# Esta célula substitui completamente a leitura do Drive.
#
# Faça upload de arquivos ZIP, um por instância.
#
# Cada ZIP deve conter:
# - nodes.csv
# - D.npy
# - Cvar.npy
# - q.npy
# - s.npy
# - params.json
# - solution_busca_local_final.json
#
# Exemplo de nomes:
# C1.zip
# C2.zip
# C3.zip
# C4.zip
#
# Também funciona com nomes como:
# COMP_ILS_C1.zip
# COMP_ILS_C2.zip

import zipfile
from pathlib import Path

print("Faça upload dos ZIPs das instâncias para análise de escalabilidade.")
print("Exemplo: C1.zip, C2.zip, C3.zip, C4.zip")

uploaded_escala = files.upload()

ESCALA_ROOT = Path("instancias_escala")
ESCALA_ROOT.mkdir(exist_ok=True)

for filename in uploaded_escala.keys():

    if not filename.lower().endswith(".zip"):
        print(f"Ignorando {filename}, pois não é ZIP.")
        continue

    nome_instancia = Path(filename).stem
    destino = ESCALA_ROOT / nome_instancia
    destino.mkdir(exist_ok=True)

    with zipfile.ZipFile(filename, "r") as zip_ref:
        zip_ref.extractall(destino)

    print(f"Extraído: {filename} → {destino}")

print("\nPastas disponíveis para escalabilidade:")
for p in sorted(ESCALA_ROOT.iterdir()):
    if p.is_dir():
        print("-", p)

# ============================================================
# (12) FUNÇÃO DE CARREGAMENTO DAS INSTÂNCIAS DE ESCALABILIDADE
# ============================================================

def find_file_recursive(folder, filename):
    """
    Procura um arquivo dentro da pasta, inclusive em subpastas.
    Isso ajuda caso o ZIP tenha uma pasta interna.
    """
    folder = Path(folder)

    matches = list(folder.rglob(filename))

    if len(matches) == 0:
        raise FileNotFoundError(f"Arquivo {filename} não encontrado em {folder}")

    return matches[0]


def load_instance_for_scalability(folder, solution_filename="solution_busca_local_final.json"):
    """
    Carrega uma instância completa a partir de uma pasta local.
    Não lê nada do Drive.
    """

    folder = Path(folder)

    nodes_path = find_file_recursive(folder, "nodes.csv")
    D_path = find_file_recursive(folder, "D.npy")
    q_path = find_file_recursive(folder, "q.npy")
    s_path = find_file_recursive(folder, "s.npy")
    params_path = find_file_recursive(folder, "params.json")

    nodes_i = pd.read_csv(nodes_path)
    D_i = np.load(D_path)
    q_i = np.load(q_path)
    s_i = np.load(s_path)

    cvar_matches = list(folder.rglob("Cvar.npy"))
    Cvar_i = np.load(cvar_matches[0]) if len(cvar_matches) > 0 else None

    with open(params_path, "r", encoding="utf-8") as f:
        params_raw_i = json.load(f)

    params_i = normalize_params(params_raw_i)

    # Procura a solução baseline
    solution_matches = list(folder.rglob(solution_filename))

    if len(solution_matches) == 0:
        # Se não encontrar exatamente esse nome, pega qualquer JSON que não seja params.json
        json_candidates = [
            p for p in folder.rglob("*.json")
            if p.name != "params.json"
        ]

        if len(json_candidates) == 0:
            raise FileNotFoundError(
                f"Nenhum JSON de solução encontrado em {folder}."
            )

        solution_path = json_candidates[0]

    else:
        solution_path = solution_matches[0]

    with open(solution_path, "r", encoding="utf-8") as f:
        sol_json_i = json.load(f)

    if isinstance(sol_json_i, dict) and "solution" in sol_json_i:
        sol_i = sol_json_i["solution"]
    else:
        sol_i = sol_json_i

    sol_i = normalize_solution(sol_i)

    return {
        "folder": str(folder),
        "nodes": nodes_i,
        "D": D_i,
        "Cvar": Cvar_i,
        "q": q_i,
        "s": s_i,
        "params": params_i,
        "baseline_solution": sol_i,
        "solution_file": str(solution_path)
    }

# ============================================================
# (13) ANÁLISE DE ESCALABILIDADE — SEM DRIVE
# ============================================================
# Esta célula roda o ILS em todas as pastas extraídas em instancias_escala.
#
# Ela compara:
# - custo da solução de busca local carregada;
# - custo após ILS;
# - ganho percentual;
# - tempo computacional;
# - número de clientes.

N_ESCALA = 80
SEED_ESCALA = SEED_FIXO

# Usa a mesma configuração de equipe definida na célula de diagnóstico.
# Exemplo: cfg = _CONFIGS[EQUIPE]
print(f"Análise de escalabilidade | equipe={EQUIPE} | N={N_ESCALA}")
print(f"Configuração usada: {cfg}")

pastas_instancias = sorted([p for p in ESCALA_ROOT.iterdir() if p.is_dir()])

if len(pastas_instancias) == 0:
    raise FileNotFoundError(
        "Nenhuma pasta de instância encontrada. "
        "Execute antes a célula de upload dos ZIPs."
    )

resultados_escala = []

print()
print(f"{'Instância':<25}|{'n_cli':>6}|{'BL (R$)':>11}|{'ILS (R$)':>11}|{'Ganho%':>9}|{'T_ILS(s)':>10}|{'Viável?':>8}")
print("-" * 90)

for pasta in pastas_instancias:

    nome_inst = pasta.name

    try:
        data_i = load_instance_for_scalability(pasta)

        D_i = data_i["D"]
        q_i = data_i["q"]
        s_i = data_i["s"]
        params_i = data_i["params"]
        sol_bl_i = data_i["baseline_solution"]

        n_cli = len(q_i) - 1

        # Confere se a solução inicial é viável
        feasible_bl = is_solution_feasible(
            sol_bl_i,
            D_i,
            q_i,
            s_i,
            params_i,
            verbose=False
        )

        if not feasible_bl:
            print(f"{nome_inst:<25}| ERRO: solução baseline inviável.")
            continue

        c_bl = total_solution_cost(sol_bl_i, D_i, params_i)

        t0 = time.time()

        sol_ils_i, hist_i = iterated_local_search(
            initial_solution=sol_bl_i,
            D=D_i,
            q=q_i,
            s=s_i,
            params=params_i,
            n_iterations=N_ESCALA,
            seed=SEED_ESCALA,
            verbose=False,
            **cfg
        )

        t_ils = time.time() - t0
        c_ils = total_solution_cost(sol_ils_i, D_i, params_i)

        feasible_ils = is_solution_feasible(
            sol_ils_i,
            D_i,
            q_i,
            s_i,
            params_i,
            verbose=False
        )

        ganho = (c_bl - c_ils) / c_bl * 100

        resultados_escala.append({
            "instancia": nome_inst,
            "n_clientes": n_cli,
            "custo_bl": c_bl,
            "custo_ils": c_ils,
            "ganho_pct": ganho,
            "t_ils": t_ils,
            "feasible_bl": feasible_bl,
            "feasible_ils": feasible_ils,
            "history": hist_i,
            "solution_ils": sol_ils_i
        })

        print(
            f"{nome_inst:<25}|{n_cli:>6}|"
            f"{c_bl:>11.2f}|{c_ils:>11.2f}|"
            f"{ganho:>8.2f}%|{t_ils:>10.2f}|{str(feasible_ils):>8}"
        )

    except Exception as e:
        print(f"{nome_inst:<25}| ERRO: {e}")

df_escala = pd.DataFrame([
    {k: v for k, v in r.items() if k not in ["history", "solution_ils"]}
    for r in resultados_escala
])

print("\nResumo:")
display(df_escala.round(3))

# ============================================================
# (14) GRÁFICOS — ANÁLISE DE ESCALABILIDADE
# ============================================================

if len(resultados_escala) == 0:
    print("Nenhum resultado de escalabilidade disponível.")
else:

    # Ordena por número de clientes
    resultados_escala = sorted(resultados_escala, key=lambda r: r["n_clientes"])

    df_escala = pd.DataFrame([
        {k: v for k, v in r.items() if k not in ["history", "solution_ils"]}
        for r in resultados_escala
    ])

    xs = df_escala["instancia"].astype(str).tolist()
    ns = df_escala["n_clientes"].values

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes = axes.flatten()

    # --------------------------------------------------------
    # Gráfico 1 — custo baseline vs ILS
    # --------------------------------------------------------
    ax = axes[0]

    x = np.arange(len(xs))
    w = 0.35

    ax.bar(
        x - w/2,
        df_escala["custo_bl"],
        w,
        label="Busca local carregada",
        color=CORES["baseline"]
    )

    ax.bar(
        x + w/2,
        df_escala["custo_ils"],
        w,
        label="Após ILS",
        color=CORES["ils"]
    )

    ax.set_xticks(x)
    ax.set_xticklabels(xs, rotation=20, ha="right")
    ax.set_ylabel("Custo total (R$)")
    ax.set_title("Custo: busca local vs. ILS por instância")
    ax.legend()
    ax.grid(True, alpha=0.3, axis="y")

    # --------------------------------------------------------
    # Gráfico 2 — ganho percentual
    # --------------------------------------------------------
    ax = axes[1]

    ax.plot(
        ns,
        df_escala["ganho_pct"],
        "o-",
        color=CORES["ils"],
        linewidth=2,
        markersize=8
    )

    for x_p, y_p, inst in zip(ns, df_escala["ganho_pct"], xs):
        ax.annotate(
            f"{y_p:.1f}%\n{inst}",
            (x_p, y_p),
            textcoords="offset points",
            xytext=(0, 10),
            ha="center",
            fontsize=9
        )

    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_xlabel("Número de clientes")
    ax.set_ylabel("Ganho do ILS sobre a busca local (%)")
    ax.set_title("Escalabilidade de qualidade\n(o ganho cresce com a instância?)")
    ax.grid(True, alpha=0.3)

    # --------------------------------------------------------
    # Gráfico 3 — tempo computacional
    # --------------------------------------------------------
    ax = axes[2]

    ax.bar(
        xs,
        df_escala["t_ils"],
        color=CORES["k1"],
        edgecolor="white"
    )

    ax.set_xticklabels(xs, rotation=20, ha="right")
    ax.set_ylabel("Tempo do ILS (s)")
    ax.set_title("Escalabilidade computacional\n(tempo gasto por instância)")
    ax.grid(True, alpha=0.3, axis="y")

    for i, v in enumerate(df_escala["t_ils"]):
        ax.text(
            i,
            v + max(df_escala["t_ils"]) * 0.02,
            f"{v:.1f}s",
            ha="center",
            fontsize=8
        )

    # --------------------------------------------------------
    # Gráfico 4 — curvas de convergência normalizadas
    # --------------------------------------------------------
    ax = axes[3]

    paleta = [CORES["k1"], CORES["k2"], CORES["k3"], CORES["k4"]]

    for idx, r in enumerate(resultados_escala):

        df_h = pd.DataFrame(r["history"])

        ax.plot(
            df_h["iteration"],
            df_h["best_cost"] / r["custo_bl"] * 100,
            color=paleta[idx % len(paleta)],
            linewidth=2,
            label=f"{r['instancia']} ({r['n_clientes']} cli)"
        )

    ax.axhline(
        100,
        color=CORES["baseline"],
        linestyle="--",
        linewidth=1.2,
        label="Busca local = 100%"
    )

    ax.set_xlabel("Iteração")
    ax.set_ylabel("Custo (% da busca local)")
    ax.set_title("Convergência normalizada por instância")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.25)

    plt.suptitle(
        f"Análise de escalabilidade — Equipe {EQUIPE}",
        fontsize=13,
        fontweight="bold"
    )

    plt.tight_layout()
    plt.savefig("escalabilidade.png", dpi=150, bbox_inches="tight")
    plt.show()

    print("Gráfico salvo: escalabilidade.png")
    display(df_escala.round(3))

# ============================================================
# (15) INTERPRETAÇÃO AUTOMÁTICA DA ESCALABILIDADE
# ============================================================

if len(resultados_escala) == 0:
    print("Nenhum resultado disponível.")
else:

    df_tmp = df_escala.sort_values("n_clientes").copy()

    menor = df_tmp.iloc[0]
    maior = df_tmp.iloc[-1]

    print("Síntese da análise de escalabilidade")
    print("─" * 60)

    print(f"Menor instância analisada: {menor['instancia']} ({int(menor['n_clientes'])} clientes)")
    print(f"Maior instância analisada: {maior['instancia']} ({int(maior['n_clientes'])} clientes)")
    print()

    print(f"Ganho na menor instância: {menor['ganho_pct']:.2f}%")
    print(f"Ganho na maior instância: {maior['ganho_pct']:.2f}%")
    print()

    if maior["ganho_pct"] > menor["ganho_pct"] + 0.5:
        print("Conclusão preliminar:")
        print("O ILS parece escalar bem em qualidade, pois o ganho percentual aumentou nas instâncias maiores.")
    elif maior["ganho_pct"] < menor["ganho_pct"] - 0.5:
        print("Conclusão preliminar:")
        print("O ganho percentual do ILS diminuiu nas instâncias maiores. Isso pode indicar que a configuração usada não está explorando bem o espaço de soluções em problemas maiores.")
    else:
        print("Conclusão preliminar:")
        print("O ganho percentual permaneceu relativamente estável com o aumento do tamanho da instância.")

    print()
    print(f"Tempo na menor instância: {menor['t_ils']:.2f} s")
    print(f"Tempo na maior instância: {maior['t_ils']:.2f} s")

    if maior["t_ils"] > menor["t_ils"] * 3:
        print("O tempo computacional cresce de forma perceptível com o tamanho da instância.")
    else:
        print("O aumento de tempo foi moderado para as instâncias avaliadas.")

    print()

"""### Outras observações pertinentes

1. **O ganho percentual do ILS aumentou com o tamanho da instância?** Se sim, o ILS é mais valioso exatamente onde a busca local sofre mais — esse é um argumento forte para a recomendação final.

2. **O tempo computacional cresceu de forma aceitável?** Qual é a estimativa para uma instância real da Prolog com 80-100 clientes?

3. **As curvas de convergência normalizadas têm formatos distintos por instância?** Instâncias maiores convergem mais devagar (mais iterações necessárias) ou mais rápido (perturbações mais eficazes)?

4. **O que mudaria na sua recomendação para instâncias grandes vs. pequenas?**

### Questões do relatório da Sprint 3 — Aulas 11 e 12

Organize as respostas em seções correspondentes às análises realizadas.

---

**[Sensibilidade — Seção 1]**

1. Qual valor de `k` produziu o menor custo na sua instância de trabalho? O resultado é consistente com a teoria (perturbações muito fracas e muito fortes são piores)?

2. A partir de qual `N` o ganho marginal caiu abaixo de 0,5%? O que isso implica sobre o número de iterações recomendado para uso operacional da Prolog?

3. Existe um `N` a partir do qual não houve nenhuma melhoria adicional? Qual é a relação entre esse ponto e o "tempo ociosa" do diagnóstico?

---

**[Convergência — Seção 2]**

4. Qual foi o diagnóstico do seu algoritmo: convergência genuína, convergência parcial ou estagnação prematura? Que evidência sustenta essa conclusão?

5. O critério de tolerância (δ=3%) produziu custo final melhor ou pior que o critério estrito? Em que tipo de instância a diferença foi maior?

6. A taxa de aceitação caiu ao longo das iterações? O que isso indica sobre a qualidade das regiões exploradas à medida que o algoritmo avança?

---

**[Escalabilidade — Seção 3]**

7. O ganho percentual do ILS sobre o baseline aumentou com o número de clientes? Esse resultado confirma ou refuta a hipótese de que o ILS é mais valioso em instâncias maiores?

8. O tempo computacional cresceu de forma linear com o número de clientes? Se a Prolog tiver 80 clientes por dia, quanto tempo o ILS levaria com sua configuração atual?

---

**[Recomendação final]**

9. Com base em todas as análises, qual configuração (perturbação + critério de aceitação + N) você recomendaria para a operação diária da Prolog? Justifique em termos de custo, tempo e robustez.

10. Existe algum cenário operacional (por ex., urgência de roteamento, tamanho de frota, período do ano) em que você recomendaria uma configuração diferente? Qual e por quê?
"""